//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace webServiceCheckOk.WsAbsolutaSolucoes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="clsLeilaoSoap", Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class clsLeilao : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InputVsBolOperationCompleted;
        
        private System.Threading.SendOrPostCallback InputVsRstOperationCompleted;
        
        private System.Threading.SendOrPostCallback InputVsDstOperationCompleted;
        
        private System.Threading.SendOrPostCallback InputVsRstFotoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InputVsDstFotoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public clsLeilao() {
            this.Url = global::webServiceCheckOk.Properties.Settings.Default.webServiceCheckOk_WsAbsolutaSolucoes_clsLeilao;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InputVsBolCompletedEventHandler InputVsBolCompleted;
        
        /// <remarks/>
        public event InputVsRstCompletedEventHandler InputVsRstCompleted;
        
        /// <remarks/>
        public event InputVsDstCompletedEventHandler InputVsDstCompleted;
        
        /// <remarks/>
        public event InputVsRstFotoCompletedEventHandler InputVsRstFotoCompleted;
        
        /// <remarks/>
        public event InputVsDstFotoCompletedEventHandler InputVsDstFotoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.absolutasolucoes.com.br/absoluta/InputVsBol", RequestNamespace="http://webservices.absolutasolucoes.com.br/absoluta/", ResponseNamespace="http://webservices.absolutasolucoes.com.br/absoluta/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public struct_RespostaBol InputVsBol(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            object[] results = this.Invoke("InputVsBol", new object[] {
                        pstrCliente,
                        pstrLogin,
                        pstrSenha,
                        pstrPlaca,
                        pstrChassi});
            return ((struct_RespostaBol)(results[0]));
        }
        
        /// <remarks/>
        public void InputVsBolAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            this.InputVsBolAsync(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi, null);
        }
        
        /// <remarks/>
        public void InputVsBolAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi, object userState) {
            if ((this.InputVsBolOperationCompleted == null)) {
                this.InputVsBolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInputVsBolOperationCompleted);
            }
            this.InvokeAsync("InputVsBol", new object[] {
                        pstrCliente,
                        pstrLogin,
                        pstrSenha,
                        pstrPlaca,
                        pstrChassi}, this.InputVsBolOperationCompleted, userState);
        }
        
        private void OnInputVsBolOperationCompleted(object arg) {
            if ((this.InputVsBolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InputVsBolCompleted(this, new InputVsBolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.absolutasolucoes.com.br/absoluta/InputVsRst", RequestNamespace="http://webservices.absolutasolucoes.com.br/absoluta/", ResponseNamespace="http://webservices.absolutasolucoes.com.br/absoluta/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public struct_RespostaRst InputVsRst(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            object[] results = this.Invoke("InputVsRst", new object[] {
                        pstrCliente,
                        pstrLogin,
                        pstrSenha,
                        pstrPlaca,
                        pstrChassi});
            return ((struct_RespostaRst)(results[0]));
        }
        
        /// <remarks/>
        public void InputVsRstAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            this.InputVsRstAsync(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi, null);
        }
        
        /// <remarks/>
        public void InputVsRstAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi, object userState) {
            if ((this.InputVsRstOperationCompleted == null)) {
                this.InputVsRstOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInputVsRstOperationCompleted);
            }
            this.InvokeAsync("InputVsRst", new object[] {
                        pstrCliente,
                        pstrLogin,
                        pstrSenha,
                        pstrPlaca,
                        pstrChassi}, this.InputVsRstOperationCompleted, userState);
        }
        
        private void OnInputVsRstOperationCompleted(object arg) {
            if ((this.InputVsRstCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InputVsRstCompleted(this, new InputVsRstCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.absolutasolucoes.com.br/absoluta/InputVsDst", RequestNamespace="http://webservices.absolutasolucoes.com.br/absoluta/", ResponseNamespace="http://webservices.absolutasolucoes.com.br/absoluta/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public struct_RespostaDst InputVsDst(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            object[] results = this.Invoke("InputVsDst", new object[] {
                        pstrCliente,
                        pstrLogin,
                        pstrSenha,
                        pstrPlaca,
                        pstrChassi});
            return ((struct_RespostaDst)(results[0]));
        }
        
        /// <remarks/>
        public void InputVsDstAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            this.InputVsDstAsync(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi, null);
        }
        
        /// <remarks/>
        public void InputVsDstAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi, object userState) {
            if ((this.InputVsDstOperationCompleted == null)) {
                this.InputVsDstOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInputVsDstOperationCompleted);
            }
            this.InvokeAsync("InputVsDst", new object[] {
                        pstrCliente,
                        pstrLogin,
                        pstrSenha,
                        pstrPlaca,
                        pstrChassi}, this.InputVsDstOperationCompleted, userState);
        }
        
        private void OnInputVsDstOperationCompleted(object arg) {
            if ((this.InputVsDstCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InputVsDstCompleted(this, new InputVsDstCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.absolutasolucoes.com.br/absoluta/InputVsRstFoto", RequestNamespace="http://webservices.absolutasolucoes.com.br/absoluta/", ResponseNamespace="http://webservices.absolutasolucoes.com.br/absoluta/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public struct_RespostaRstFoto InputVsRstFoto(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            object[] results = this.Invoke("InputVsRstFoto", new object[] {
                        pstrCliente,
                        pstrLogin,
                        pstrSenha,
                        pstrPlaca,
                        pstrChassi});
            return ((struct_RespostaRstFoto)(results[0]));
        }
        
        /// <remarks/>
        public void InputVsRstFotoAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            this.InputVsRstFotoAsync(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi, null);
        }
        
        /// <remarks/>
        public void InputVsRstFotoAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi, object userState) {
            if ((this.InputVsRstFotoOperationCompleted == null)) {
                this.InputVsRstFotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInputVsRstFotoOperationCompleted);
            }
            this.InvokeAsync("InputVsRstFoto", new object[] {
                        pstrCliente,
                        pstrLogin,
                        pstrSenha,
                        pstrPlaca,
                        pstrChassi}, this.InputVsRstFotoOperationCompleted, userState);
        }
        
        private void OnInputVsRstFotoOperationCompleted(object arg) {
            if ((this.InputVsRstFotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InputVsRstFotoCompleted(this, new InputVsRstFotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.absolutasolucoes.com.br/absoluta/InputVsDstFoto", RequestNamespace="http://webservices.absolutasolucoes.com.br/absoluta/", ResponseNamespace="http://webservices.absolutasolucoes.com.br/absoluta/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public struct_RespostaDst InputVsDstFoto(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            object[] results = this.Invoke("InputVsDstFoto", new object[] {
                        pstrCliente,
                        pstrLogin,
                        pstrSenha,
                        pstrPlaca,
                        pstrChassi});
            return ((struct_RespostaDst)(results[0]));
        }
        
        /// <remarks/>
        public void InputVsDstFotoAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            this.InputVsDstFotoAsync(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi, null);
        }
        
        /// <remarks/>
        public void InputVsDstFotoAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi, object userState) {
            if ((this.InputVsDstFotoOperationCompleted == null)) {
                this.InputVsDstFotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInputVsDstFotoOperationCompleted);
            }
            this.InvokeAsync("InputVsDstFoto", new object[] {
                        pstrCliente,
                        pstrLogin,
                        pstrSenha,
                        pstrPlaca,
                        pstrChassi}, this.InputVsDstFotoOperationCompleted, userState);
        }
        
        private void OnInputVsDstFotoOperationCompleted(object arg) {
            if ((this.InputVsDstFotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InputVsDstFotoCompleted(this, new InputVsDstFotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_RespostaBol {
        
        private struct_Identificacao identificacaoField;
        
        private struct_Controle controleField;
        
        private bool respostaField;
        
        /// <remarks/>
        public struct_Identificacao Identificacao {
            get {
                return this.identificacaoField;
            }
            set {
                this.identificacaoField = value;
            }
        }
        
        /// <remarks/>
        public struct_Controle Controle {
            get {
                return this.controleField;
            }
            set {
                this.controleField = value;
            }
        }
        
        /// <remarks/>
        public bool Resposta {
            get {
                return this.respostaField;
            }
            set {
                this.respostaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_Identificacao {
        
        private string nomeDaTransacaoField;
        
        private string descricaoDaTransacaoField;
        
        private string versaoDaTransacaoField;
        
        private System.DateTime dataDaPublicacaoField;
        
        private string autorField;
        
        /// <remarks/>
        public string NomeDaTransacao {
            get {
                return this.nomeDaTransacaoField;
            }
            set {
                this.nomeDaTransacaoField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoDaTransacao {
            get {
                return this.descricaoDaTransacaoField;
            }
            set {
                this.descricaoDaTransacaoField = value;
            }
        }
        
        /// <remarks/>
        public string VersaoDaTransacao {
            get {
                return this.versaoDaTransacaoField;
            }
            set {
                this.versaoDaTransacaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataDaPublicacao {
            get {
                return this.dataDaPublicacaoField;
            }
            set {
                this.dataDaPublicacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_LeilaoFoto {
        
        private long nsuVeiculoField;
        
        private long idLeilaoField;
        
        private string loteField;
        
        private string marcaField;
        
        private string modeloField;
        
        private int anoModeloField;
        
        private int anoFabricacaoField;
        
        private string placaField;
        
        private string chassiField;
        
        private string renavamField;
        
        private string corField;
        
        private string combustivelField;
        
        private string categoriaDoVeiculoField;
        
        private string condicaoGeralDoVeiculoField;
        
        private string situacaoDoChassiField;
        
        private string nrMotorField;
        
        private string nrCambioField;
        
        private string nrCarroceriaField;
        
        private string nrEixoTraseiroField;
        
        private int quantidadeDeEixosField;
        
        private string patioField;
        
        private string leiloeiroField;
        
        private System.DateTime dataLeilaoField;
        
        private string comitenteField;
        
        private string nomeFoto1Field;
        
        private string nomeFoto2Field;
        
        private string nomeFoto3Field;
        
        private string nomeFoto4Field;
        
        private string urlFoto1Field;
        
        private string urlFoto2Field;
        
        private string urlFoto3Field;
        
        private string urlFoto4Field;
        
        /// <remarks/>
        public long NsuVeiculo {
            get {
                return this.nsuVeiculoField;
            }
            set {
                this.nsuVeiculoField = value;
            }
        }
        
        /// <remarks/>
        public long IdLeilao {
            get {
                return this.idLeilaoField;
            }
            set {
                this.idLeilaoField = value;
            }
        }
        
        /// <remarks/>
        public string Lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
            }
        }
        
        /// <remarks/>
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public int AnoModelo {
            get {
                return this.anoModeloField;
            }
            set {
                this.anoModeloField = value;
            }
        }
        
        /// <remarks/>
        public int AnoFabricacao {
            get {
                return this.anoFabricacaoField;
            }
            set {
                this.anoFabricacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string Chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        public string Renavam {
            get {
                return this.renavamField;
            }
            set {
                this.renavamField = value;
            }
        }
        
        /// <remarks/>
        public string Cor {
            get {
                return this.corField;
            }
            set {
                this.corField = value;
            }
        }
        
        /// <remarks/>
        public string Combustivel {
            get {
                return this.combustivelField;
            }
            set {
                this.combustivelField = value;
            }
        }
        
        /// <remarks/>
        public string CategoriaDoVeiculo {
            get {
                return this.categoriaDoVeiculoField;
            }
            set {
                this.categoriaDoVeiculoField = value;
            }
        }
        
        /// <remarks/>
        public string CondicaoGeralDoVeiculo {
            get {
                return this.condicaoGeralDoVeiculoField;
            }
            set {
                this.condicaoGeralDoVeiculoField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoDoChassi {
            get {
                return this.situacaoDoChassiField;
            }
            set {
                this.situacaoDoChassiField = value;
            }
        }
        
        /// <remarks/>
        public string NrMotor {
            get {
                return this.nrMotorField;
            }
            set {
                this.nrMotorField = value;
            }
        }
        
        /// <remarks/>
        public string NrCambio {
            get {
                return this.nrCambioField;
            }
            set {
                this.nrCambioField = value;
            }
        }
        
        /// <remarks/>
        public string NrCarroceria {
            get {
                return this.nrCarroceriaField;
            }
            set {
                this.nrCarroceriaField = value;
            }
        }
        
        /// <remarks/>
        public string NrEixoTraseiro {
            get {
                return this.nrEixoTraseiroField;
            }
            set {
                this.nrEixoTraseiroField = value;
            }
        }
        
        /// <remarks/>
        public int QuantidadeDeEixos {
            get {
                return this.quantidadeDeEixosField;
            }
            set {
                this.quantidadeDeEixosField = value;
            }
        }
        
        /// <remarks/>
        public string Patio {
            get {
                return this.patioField;
            }
            set {
                this.patioField = value;
            }
        }
        
        /// <remarks/>
        public string Leiloeiro {
            get {
                return this.leiloeiroField;
            }
            set {
                this.leiloeiroField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataLeilao {
            get {
                return this.dataLeilaoField;
            }
            set {
                this.dataLeilaoField = value;
            }
        }
        
        /// <remarks/>
        public string Comitente {
            get {
                return this.comitenteField;
            }
            set {
                this.comitenteField = value;
            }
        }
        
        /// <remarks/>
        public string NomeFoto1 {
            get {
                return this.nomeFoto1Field;
            }
            set {
                this.nomeFoto1Field = value;
            }
        }
        
        /// <remarks/>
        public string NomeFoto2 {
            get {
                return this.nomeFoto2Field;
            }
            set {
                this.nomeFoto2Field = value;
            }
        }
        
        /// <remarks/>
        public string NomeFoto3 {
            get {
                return this.nomeFoto3Field;
            }
            set {
                this.nomeFoto3Field = value;
            }
        }
        
        /// <remarks/>
        public string NomeFoto4 {
            get {
                return this.nomeFoto4Field;
            }
            set {
                this.nomeFoto4Field = value;
            }
        }
        
        /// <remarks/>
        public string UrlFoto1 {
            get {
                return this.urlFoto1Field;
            }
            set {
                this.urlFoto1Field = value;
            }
        }
        
        /// <remarks/>
        public string UrlFoto2 {
            get {
                return this.urlFoto2Field;
            }
            set {
                this.urlFoto2Field = value;
            }
        }
        
        /// <remarks/>
        public string UrlFoto3 {
            get {
                return this.urlFoto3Field;
            }
            set {
                this.urlFoto3Field = value;
            }
        }
        
        /// <remarks/>
        public string UrlFoto4 {
            get {
                return this.urlFoto4Field;
            }
            set {
                this.urlFoto4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_RespostaRstFoto {
        
        private struct_Identificacao identificacaoField;
        
        private struct_Controle controleField;
        
        private struct_LeilaoFoto[] respostaField;
        
        /// <remarks/>
        public struct_Identificacao Identificacao {
            get {
                return this.identificacaoField;
            }
            set {
                this.identificacaoField = value;
            }
        }
        
        /// <remarks/>
        public struct_Controle Controle {
            get {
                return this.controleField;
            }
            set {
                this.controleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public struct_LeilaoFoto[] Resposta {
            get {
                return this.respostaField;
            }
            set {
                this.respostaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_Controle {
        
        private int codigoDeControleField;
        
        private e_Severidade severidadeField;
        
        private string descricaoField;
        
        private e_Acao acaoAdotadaField;
        
        private e_ResultadoDaPesquisa resultadoDaPesquisaField;
        
        private e_GravacaoDeLog gravacaoDoLogField;
        
        private System.DateTime dataExecucaoField;
        
        private string observacaoField;
        
        /// <remarks/>
        public int CodigoDeControle {
            get {
                return this.codigoDeControleField;
            }
            set {
                this.codigoDeControleField = value;
            }
        }
        
        /// <remarks/>
        public e_Severidade Severidade {
            get {
                return this.severidadeField;
            }
            set {
                this.severidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public e_Acao AcaoAdotada {
            get {
                return this.acaoAdotadaField;
            }
            set {
                this.acaoAdotadaField = value;
            }
        }
        
        /// <remarks/>
        public e_ResultadoDaPesquisa ResultadoDaPesquisa {
            get {
                return this.resultadoDaPesquisaField;
            }
            set {
                this.resultadoDaPesquisaField = value;
            }
        }
        
        /// <remarks/>
        public e_GravacaoDeLog GravacaoDoLog {
            get {
                return this.gravacaoDoLogField;
            }
            set {
                this.gravacaoDoLogField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataExecucao {
            get {
                return this.dataExecucaoField;
            }
            set {
                this.dataExecucaoField = value;
            }
        }
        
        /// <remarks/>
        public string Observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public enum e_Severidade {
        
        /// <remarks/>
        e0_NumeradorNaoInicializado,
        
        /// <remarks/>
        e1_MensagemDeInformacaoSimples,
        
        /// <remarks/>
        e2_MensagemDeAdvertencia,
        
        /// <remarks/>
        e3_MensagemDeErro,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public enum e_Acao {
        
        /// <remarks/>
        e0_NumeradorNaoInicializado,
        
        /// <remarks/>
        e1_TrasacaoFoiExecutada,
        
        /// <remarks/>
        e2_TransacaoNaoFoiExecutada,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public enum e_ResultadoDaPesquisa {
        
        /// <remarks/>
        e0_NumeradorNaoInicializado,
        
        /// <remarks/>
        e1_RegistrosForamLocalizados,
        
        /// <remarks/>
        e2_RegistrosNaoForamLocalizados,
        
        /// <remarks/>
        e3_RegistrosNemForamPesquisados,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public enum e_GravacaoDeLog {
        
        /// <remarks/>
        e0_NumeradorNaoInicializado,
        
        /// <remarks/>
        e1_TransacaoFoiLogada,
        
        /// <remarks/>
        e2_TransacaoNaoFoiLogada,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_RespostaDst {
        
        private struct_Identificacao identificacaoField;
        
        private struct_Controle controleField;
        
        private System.Data.DataSet respostaField;
        
        /// <remarks/>
        public struct_Identificacao Identificacao {
            get {
                return this.identificacaoField;
            }
            set {
                this.identificacaoField = value;
            }
        }
        
        /// <remarks/>
        public struct_Controle Controle {
            get {
                return this.controleField;
            }
            set {
                this.controleField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet Resposta {
            get {
                return this.respostaField;
            }
            set {
                this.respostaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_Leilao {
        
        private long nsuVeiculoField;
        
        private long idLeilaoField;
        
        private string loteField;
        
        private string marcaField;
        
        private string modeloField;
        
        private int anoModeloField;
        
        private int anoFabricacaoField;
        
        private string placaField;
        
        private string chassiField;
        
        private string renavamField;
        
        private string corField;
        
        private string combustivelField;
        
        private string categoriaDoVeiculoField;
        
        private string condicaoGeralDoVeiculoField;
        
        private string situacaoDoChassiField;
        
        private string nrMotorField;
        
        private string nrCambioField;
        
        private string nrCarroceriaField;
        
        private string nrEixoTraseiroField;
        
        private int quantidadeDeEixosField;
        
        private string patioField;
        
        private string leiloeiroField;
        
        private System.DateTime dataLeilaoField;
        
        private string comitenteField;
        
        /// <remarks/>
        public long NsuVeiculo {
            get {
                return this.nsuVeiculoField;
            }
            set {
                this.nsuVeiculoField = value;
            }
        }
        
        /// <remarks/>
        public long IdLeilao {
            get {
                return this.idLeilaoField;
            }
            set {
                this.idLeilaoField = value;
            }
        }
        
        /// <remarks/>
        public string Lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
            }
        }
        
        /// <remarks/>
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public int AnoModelo {
            get {
                return this.anoModeloField;
            }
            set {
                this.anoModeloField = value;
            }
        }
        
        /// <remarks/>
        public int AnoFabricacao {
            get {
                return this.anoFabricacaoField;
            }
            set {
                this.anoFabricacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string Chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        public string Renavam {
            get {
                return this.renavamField;
            }
            set {
                this.renavamField = value;
            }
        }
        
        /// <remarks/>
        public string Cor {
            get {
                return this.corField;
            }
            set {
                this.corField = value;
            }
        }
        
        /// <remarks/>
        public string Combustivel {
            get {
                return this.combustivelField;
            }
            set {
                this.combustivelField = value;
            }
        }
        
        /// <remarks/>
        public string CategoriaDoVeiculo {
            get {
                return this.categoriaDoVeiculoField;
            }
            set {
                this.categoriaDoVeiculoField = value;
            }
        }
        
        /// <remarks/>
        public string CondicaoGeralDoVeiculo {
            get {
                return this.condicaoGeralDoVeiculoField;
            }
            set {
                this.condicaoGeralDoVeiculoField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoDoChassi {
            get {
                return this.situacaoDoChassiField;
            }
            set {
                this.situacaoDoChassiField = value;
            }
        }
        
        /// <remarks/>
        public string NrMotor {
            get {
                return this.nrMotorField;
            }
            set {
                this.nrMotorField = value;
            }
        }
        
        /// <remarks/>
        public string NrCambio {
            get {
                return this.nrCambioField;
            }
            set {
                this.nrCambioField = value;
            }
        }
        
        /// <remarks/>
        public string NrCarroceria {
            get {
                return this.nrCarroceriaField;
            }
            set {
                this.nrCarroceriaField = value;
            }
        }
        
        /// <remarks/>
        public string NrEixoTraseiro {
            get {
                return this.nrEixoTraseiroField;
            }
            set {
                this.nrEixoTraseiroField = value;
            }
        }
        
        /// <remarks/>
        public int QuantidadeDeEixos {
            get {
                return this.quantidadeDeEixosField;
            }
            set {
                this.quantidadeDeEixosField = value;
            }
        }
        
        /// <remarks/>
        public string Patio {
            get {
                return this.patioField;
            }
            set {
                this.patioField = value;
            }
        }
        
        /// <remarks/>
        public string Leiloeiro {
            get {
                return this.leiloeiroField;
            }
            set {
                this.leiloeiroField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataLeilao {
            get {
                return this.dataLeilaoField;
            }
            set {
                this.dataLeilaoField = value;
            }
        }
        
        /// <remarks/>
        public string Comitente {
            get {
                return this.comitenteField;
            }
            set {
                this.comitenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.absolutasolucoes.com.br/absoluta/")]
    public partial class struct_RespostaRst {
        
        private struct_Identificacao identificacaoField;
        
        private struct_Controle controleField;
        
        private struct_Leilao[] respostaField;
        
        /// <remarks/>
        public struct_Identificacao Identificacao {
            get {
                return this.identificacaoField;
            }
            set {
                this.identificacaoField = value;
            }
        }
        
        /// <remarks/>
        public struct_Controle Controle {
            get {
                return this.controleField;
            }
            set {
                this.controleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public struct_Leilao[] Resposta {
            get {
                return this.respostaField;
            }
            set {
                this.respostaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void InputVsBolCompletedEventHandler(object sender, InputVsBolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InputVsBolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InputVsBolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public struct_RespostaBol Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((struct_RespostaBol)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void InputVsRstCompletedEventHandler(object sender, InputVsRstCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InputVsRstCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InputVsRstCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public struct_RespostaRst Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((struct_RespostaRst)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void InputVsDstCompletedEventHandler(object sender, InputVsDstCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InputVsDstCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InputVsDstCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public struct_RespostaDst Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((struct_RespostaDst)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void InputVsRstFotoCompletedEventHandler(object sender, InputVsRstFotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InputVsRstFotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InputVsRstFotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public struct_RespostaRstFoto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((struct_RespostaRstFoto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void InputVsDstFotoCompletedEventHandler(object sender, InputVsDstFotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InputVsDstFotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InputVsDstFotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public struct_RespostaDst Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((struct_RespostaDst)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591