//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace webServiceCheckOk.WsSinaliza {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultasVeiculosSoap", Namespace="http://tempuri.org/")]
    public partial class ConsultasVeiculos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback ConsultaSinalizaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaSinaliza1OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultasVeiculos() {
            this.Url = global::webServiceCheckOk.Properties.Settings.Default.webServiceCheckOk_WsSinaliza_ConsultasVeiculos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaSinalizaCompletedEventHandler ConsultaSinalizaCompleted;
        
        /// <remarks/>
        public event ConsultaSinaliza1CompletedEventHandler ConsultaSinaliza1Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PesquisaOutrasChaves", RequestElementName="PesquisaOutrasChaves", RequestNamespace="http://tempuri.org/", ResponseElementName="PesquisaOutrasChavesResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PesquisaOutrasChavesResult")]
        public string ConsultaSinaliza(int IntIdProduto, string strPlaca, string strChassi, string strNumCarroceria, string strNumCxCambio, string strNumEixoTras, string strNumTercEixo, string strNumMotor) {
            object[] results = this.Invoke("ConsultaSinaliza", new object[] {
                        IntIdProduto,
                        strPlaca,
                        strChassi,
                        strNumCarroceria,
                        strNumCxCambio,
                        strNumEixoTras,
                        strNumTercEixo,
                        strNumMotor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaSinalizaAsync(int IntIdProduto, string strPlaca, string strChassi, string strNumCarroceria, string strNumCxCambio, string strNumEixoTras, string strNumTercEixo, string strNumMotor) {
            this.ConsultaSinalizaAsync(IntIdProduto, strPlaca, strChassi, strNumCarroceria, strNumCxCambio, strNumEixoTras, strNumTercEixo, strNumMotor, null);
        }
        
        /// <remarks/>
        public void ConsultaSinalizaAsync(int IntIdProduto, string strPlaca, string strChassi, string strNumCarroceria, string strNumCxCambio, string strNumEixoTras, string strNumTercEixo, string strNumMotor, object userState) {
            if ((this.ConsultaSinalizaOperationCompleted == null)) {
                this.ConsultaSinalizaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaSinalizaOperationCompleted);
            }
            this.InvokeAsync("ConsultaSinaliza", new object[] {
                        IntIdProduto,
                        strPlaca,
                        strChassi,
                        strNumCarroceria,
                        strNumCxCambio,
                        strNumEixoTras,
                        strNumTercEixo,
                        strNumMotor}, this.ConsultaSinalizaOperationCompleted, userState);
        }
        
        private void OnConsultaSinalizaOperationCompleted(object arg) {
            if ((this.ConsultaSinalizaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaSinalizaCompleted(this, new ConsultaSinalizaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="ConsultaSinaliza1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaSinaliza", RequestElementName="ConsultaSinaliza", RequestNamespace="http://tempuri.org/", ResponseElementName="ConsultaSinalizaResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ConsultaSinalizaResult")]
        public string ConsultaSinaliza(int IntIdProduto, string strPlaca, string strChassi, string strUF, int intCodMunic) {
            object[] results = this.Invoke("ConsultaSinaliza1", new object[] {
                        IntIdProduto,
                        strPlaca,
                        strChassi,
                        strUF,
                        intCodMunic});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaSinaliza1Async(int IntIdProduto, string strPlaca, string strChassi, string strUF, int intCodMunic) {
            this.ConsultaSinaliza1Async(IntIdProduto, strPlaca, strChassi, strUF, intCodMunic, null);
        }
        
        /// <remarks/>
        public void ConsultaSinaliza1Async(int IntIdProduto, string strPlaca, string strChassi, string strUF, int intCodMunic, object userState) {
            if ((this.ConsultaSinaliza1OperationCompleted == null)) {
                this.ConsultaSinaliza1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaSinaliza1OperationCompleted);
            }
            this.InvokeAsync("ConsultaSinaliza1", new object[] {
                        IntIdProduto,
                        strPlaca,
                        strChassi,
                        strUF,
                        intCodMunic}, this.ConsultaSinaliza1OperationCompleted, userState);
        }
        
        private void OnConsultaSinaliza1OperationCompleted(object arg) {
            if ((this.ConsultaSinaliza1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaSinaliza1Completed(this, new ConsultaSinaliza1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usuarioField;
        
        private string senhaField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaSinalizaCompletedEventHandler(object sender, ConsultaSinalizaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaSinalizaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaSinalizaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaSinaliza1CompletedEventHandler(object sender, ConsultaSinaliza1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaSinaliza1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaSinaliza1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591