//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace webServiceCheckOk.WsCheckPro {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaBaseEstadualPorChassiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBaseEstadualPorPlacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBaseNacionalPorCaixaCambioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBaseNacionalPorMotorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBaseNacionalPorChassiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBaseNacionalPorPlacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBdrfPorChassiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBdrfPorPlacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBdsiiPorChassiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBdsiiPorPlacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaCnhPorCpfOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDecodChassiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDpvatPorChassiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDpvatPorCnpjOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDpvatPorCpfOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDpvatPorPlacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaLeilaoPorChassiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaLeilaoPorPlacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaCpfOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::webServiceCheckOk.Properties.Settings.Default.webServiceCheckOk_WsCheckPro_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaBaseEstadualPorChassiCompletedEventHandler ConsultaBaseEstadualPorChassiCompleted;
        
        /// <remarks/>
        public event ConsultaBaseEstadualPorPlacaCompletedEventHandler ConsultaBaseEstadualPorPlacaCompleted;
        
        /// <remarks/>
        public event ConsultaBaseNacionalPorCaixaCambioCompletedEventHandler ConsultaBaseNacionalPorCaixaCambioCompleted;
        
        /// <remarks/>
        public event ConsultaBaseNacionalPorMotorCompletedEventHandler ConsultaBaseNacionalPorMotorCompleted;
        
        /// <remarks/>
        public event ConsultaBaseNacionalPorChassiCompletedEventHandler ConsultaBaseNacionalPorChassiCompleted;
        
        /// <remarks/>
        public event ConsultaBaseNacionalPorPlacaCompletedEventHandler ConsultaBaseNacionalPorPlacaCompleted;
        
        /// <remarks/>
        public event ConsultaBdrfPorChassiCompletedEventHandler ConsultaBdrfPorChassiCompleted;
        
        /// <remarks/>
        public event ConsultaBdrfPorPlacaCompletedEventHandler ConsultaBdrfPorPlacaCompleted;
        
        /// <remarks/>
        public event ConsultaBdsiiPorChassiCompletedEventHandler ConsultaBdsiiPorChassiCompleted;
        
        /// <remarks/>
        public event ConsultaBdsiiPorPlacaCompletedEventHandler ConsultaBdsiiPorPlacaCompleted;
        
        /// <remarks/>
        public event ConsultaCnhPorCpfCompletedEventHandler ConsultaCnhPorCpfCompleted;
        
        /// <remarks/>
        public event ConsultaDecodChassiCompletedEventHandler ConsultaDecodChassiCompleted;
        
        /// <remarks/>
        public event ConsultaDpvatPorChassiCompletedEventHandler ConsultaDpvatPorChassiCompleted;
        
        /// <remarks/>
        public event ConsultaDpvatPorCnpjCompletedEventHandler ConsultaDpvatPorCnpjCompleted;
        
        /// <remarks/>
        public event ConsultaDpvatPorCpfCompletedEventHandler ConsultaDpvatPorCpfCompleted;
        
        /// <remarks/>
        public event ConsultaDpvatPorPlacaCompletedEventHandler ConsultaDpvatPorPlacaCompleted;
        
        /// <remarks/>
        public event ConsultaLeilaoPorChassiCompletedEventHandler ConsultaLeilaoPorChassiCompleted;
        
        /// <remarks/>
        public event ConsultaLeilaoPorPlacaCompletedEventHandler ConsultaLeilaoPorPlacaCompleted;
        
        /// <remarks/>
        public event ConsultaCpfCompletedEventHandler ConsultaCpfCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaBaseEstadualPorChassi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaBaseEstadualPorChassi(string cpfUsuario, string senhaUsuario, string chassi, string uf) {
            object[] results = this.Invoke("ConsultaBaseEstadualPorChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        chassi,
                        uf});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBaseEstadualPorChassiAsync(string cpfUsuario, string senhaUsuario, string chassi, string uf) {
            this.ConsultaBaseEstadualPorChassiAsync(cpfUsuario, senhaUsuario, chassi, uf, null);
        }
        
        /// <remarks/>
        public void ConsultaBaseEstadualPorChassiAsync(string cpfUsuario, string senhaUsuario, string chassi, string uf, object userState) {
            if ((this.ConsultaBaseEstadualPorChassiOperationCompleted == null)) {
                this.ConsultaBaseEstadualPorChassiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBaseEstadualPorChassiOperationCompleted);
            }
            this.InvokeAsync("ConsultaBaseEstadualPorChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        chassi,
                        uf}, this.ConsultaBaseEstadualPorChassiOperationCompleted, userState);
        }
        
        private void OnConsultaBaseEstadualPorChassiOperationCompleted(object arg) {
            if ((this.ConsultaBaseEstadualPorChassiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBaseEstadualPorChassiCompleted(this, new ConsultaBaseEstadualPorChassiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaBaseEstadualPorPlaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaBaseEstadualPorPlaca(string cpfUsuario, string senhaUsuario, string placa, string uf) {
            object[] results = this.Invoke("ConsultaBaseEstadualPorPlaca", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        placa,
                        uf});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBaseEstadualPorPlacaAsync(string cpfUsuario, string senhaUsuario, string placa, string uf) {
            this.ConsultaBaseEstadualPorPlacaAsync(cpfUsuario, senhaUsuario, placa, uf, null);
        }
        
        /// <remarks/>
        public void ConsultaBaseEstadualPorPlacaAsync(string cpfUsuario, string senhaUsuario, string placa, string uf, object userState) {
            if ((this.ConsultaBaseEstadualPorPlacaOperationCompleted == null)) {
                this.ConsultaBaseEstadualPorPlacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBaseEstadualPorPlacaOperationCompleted);
            }
            this.InvokeAsync("ConsultaBaseEstadualPorPlaca", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        placa,
                        uf}, this.ConsultaBaseEstadualPorPlacaOperationCompleted, userState);
        }
        
        private void OnConsultaBaseEstadualPorPlacaOperationCompleted(object arg) {
            if ((this.ConsultaBaseEstadualPorPlacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBaseEstadualPorPlacaCompleted(this, new ConsultaBaseEstadualPorPlacaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaBaseNacionalPorCaixaCambio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaBaseNacionalPorCaixaCambio(string cpfUsuario, string senhaUsuario, string cxCambio) {
            object[] results = this.Invoke("ConsultaBaseNacionalPorCaixaCambio", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        cxCambio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBaseNacionalPorCaixaCambioAsync(string cpfUsuario, string senhaUsuario, string cxCambio) {
            this.ConsultaBaseNacionalPorCaixaCambioAsync(cpfUsuario, senhaUsuario, cxCambio, null);
        }
        
        /// <remarks/>
        public void ConsultaBaseNacionalPorCaixaCambioAsync(string cpfUsuario, string senhaUsuario, string cxCambio, object userState) {
            if ((this.ConsultaBaseNacionalPorCaixaCambioOperationCompleted == null)) {
                this.ConsultaBaseNacionalPorCaixaCambioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBaseNacionalPorCaixaCambioOperationCompleted);
            }
            this.InvokeAsync("ConsultaBaseNacionalPorCaixaCambio", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        cxCambio}, this.ConsultaBaseNacionalPorCaixaCambioOperationCompleted, userState);
        }
        
        private void OnConsultaBaseNacionalPorCaixaCambioOperationCompleted(object arg) {
            if ((this.ConsultaBaseNacionalPorCaixaCambioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBaseNacionalPorCaixaCambioCompleted(this, new ConsultaBaseNacionalPorCaixaCambioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaBaseNacionalPorMotor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaBaseNacionalPorMotor(string cpfUsuario, string senhaUsuario, string motor) {
            object[] results = this.Invoke("ConsultaBaseNacionalPorMotor", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        motor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBaseNacionalPorMotorAsync(string cpfUsuario, string senhaUsuario, string motor) {
            this.ConsultaBaseNacionalPorMotorAsync(cpfUsuario, senhaUsuario, motor, null);
        }
        
        /// <remarks/>
        public void ConsultaBaseNacionalPorMotorAsync(string cpfUsuario, string senhaUsuario, string motor, object userState) {
            if ((this.ConsultaBaseNacionalPorMotorOperationCompleted == null)) {
                this.ConsultaBaseNacionalPorMotorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBaseNacionalPorMotorOperationCompleted);
            }
            this.InvokeAsync("ConsultaBaseNacionalPorMotor", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        motor}, this.ConsultaBaseNacionalPorMotorOperationCompleted, userState);
        }
        
        private void OnConsultaBaseNacionalPorMotorOperationCompleted(object arg) {
            if ((this.ConsultaBaseNacionalPorMotorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBaseNacionalPorMotorCompleted(this, new ConsultaBaseNacionalPorMotorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaBaseNacionalPorChassi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaBaseNacionalPorChassi(string cpfUsuario, string senhaUsuario, string chassi) {
            object[] results = this.Invoke("ConsultaBaseNacionalPorChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        chassi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBaseNacionalPorChassiAsync(string cpfUsuario, string senhaUsuario, string chassi) {
            this.ConsultaBaseNacionalPorChassiAsync(cpfUsuario, senhaUsuario, chassi, null);
        }
        
        /// <remarks/>
        public void ConsultaBaseNacionalPorChassiAsync(string cpfUsuario, string senhaUsuario, string chassi, object userState) {
            if ((this.ConsultaBaseNacionalPorChassiOperationCompleted == null)) {
                this.ConsultaBaseNacionalPorChassiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBaseNacionalPorChassiOperationCompleted);
            }
            this.InvokeAsync("ConsultaBaseNacionalPorChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        chassi}, this.ConsultaBaseNacionalPorChassiOperationCompleted, userState);
        }
        
        private void OnConsultaBaseNacionalPorChassiOperationCompleted(object arg) {
            if ((this.ConsultaBaseNacionalPorChassiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBaseNacionalPorChassiCompleted(this, new ConsultaBaseNacionalPorChassiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaBaseNacionalPorPlaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaBaseNacionalPorPlaca(string cpfUsuario, string senhaUsuario, string placa) {
            object[] results = this.Invoke("ConsultaBaseNacionalPorPlaca", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        placa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBaseNacionalPorPlacaAsync(string cpfUsuario, string senhaUsuario, string placa) {
            this.ConsultaBaseNacionalPorPlacaAsync(cpfUsuario, senhaUsuario, placa, null);
        }
        
        /// <remarks/>
        public void ConsultaBaseNacionalPorPlacaAsync(string cpfUsuario, string senhaUsuario, string placa, object userState) {
            if ((this.ConsultaBaseNacionalPorPlacaOperationCompleted == null)) {
                this.ConsultaBaseNacionalPorPlacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBaseNacionalPorPlacaOperationCompleted);
            }
            this.InvokeAsync("ConsultaBaseNacionalPorPlaca", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        placa}, this.ConsultaBaseNacionalPorPlacaOperationCompleted, userState);
        }
        
        private void OnConsultaBaseNacionalPorPlacaOperationCompleted(object arg) {
            if ((this.ConsultaBaseNacionalPorPlacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBaseNacionalPorPlacaCompleted(this, new ConsultaBaseNacionalPorPlacaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaBdrfPorChassi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaBdrfPorChassi(string cpfUsuario, string senhaUsuario, string chassi) {
            object[] results = this.Invoke("ConsultaBdrfPorChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        chassi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBdrfPorChassiAsync(string cpfUsuario, string senhaUsuario, string chassi) {
            this.ConsultaBdrfPorChassiAsync(cpfUsuario, senhaUsuario, chassi, null);
        }
        
        /// <remarks/>
        public void ConsultaBdrfPorChassiAsync(string cpfUsuario, string senhaUsuario, string chassi, object userState) {
            if ((this.ConsultaBdrfPorChassiOperationCompleted == null)) {
                this.ConsultaBdrfPorChassiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBdrfPorChassiOperationCompleted);
            }
            this.InvokeAsync("ConsultaBdrfPorChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        chassi}, this.ConsultaBdrfPorChassiOperationCompleted, userState);
        }
        
        private void OnConsultaBdrfPorChassiOperationCompleted(object arg) {
            if ((this.ConsultaBdrfPorChassiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBdrfPorChassiCompleted(this, new ConsultaBdrfPorChassiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaBdrfPorPlaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaBdrfPorPlaca(string cpfUsuario, string senhaUsuario, string placa) {
            object[] results = this.Invoke("ConsultaBdrfPorPlaca", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        placa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBdrfPorPlacaAsync(string cpfUsuario, string senhaUsuario, string placa) {
            this.ConsultaBdrfPorPlacaAsync(cpfUsuario, senhaUsuario, placa, null);
        }
        
        /// <remarks/>
        public void ConsultaBdrfPorPlacaAsync(string cpfUsuario, string senhaUsuario, string placa, object userState) {
            if ((this.ConsultaBdrfPorPlacaOperationCompleted == null)) {
                this.ConsultaBdrfPorPlacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBdrfPorPlacaOperationCompleted);
            }
            this.InvokeAsync("ConsultaBdrfPorPlaca", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        placa}, this.ConsultaBdrfPorPlacaOperationCompleted, userState);
        }
        
        private void OnConsultaBdrfPorPlacaOperationCompleted(object arg) {
            if ((this.ConsultaBdrfPorPlacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBdrfPorPlacaCompleted(this, new ConsultaBdrfPorPlacaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaBdsiiPorChassi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaBdsiiPorChassi(string cpfUsuario, string senhaUsuario, string chassi) {
            object[] results = this.Invoke("ConsultaBdsiiPorChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        chassi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBdsiiPorChassiAsync(string cpfUsuario, string senhaUsuario, string chassi) {
            this.ConsultaBdsiiPorChassiAsync(cpfUsuario, senhaUsuario, chassi, null);
        }
        
        /// <remarks/>
        public void ConsultaBdsiiPorChassiAsync(string cpfUsuario, string senhaUsuario, string chassi, object userState) {
            if ((this.ConsultaBdsiiPorChassiOperationCompleted == null)) {
                this.ConsultaBdsiiPorChassiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBdsiiPorChassiOperationCompleted);
            }
            this.InvokeAsync("ConsultaBdsiiPorChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        chassi}, this.ConsultaBdsiiPorChassiOperationCompleted, userState);
        }
        
        private void OnConsultaBdsiiPorChassiOperationCompleted(object arg) {
            if ((this.ConsultaBdsiiPorChassiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBdsiiPorChassiCompleted(this, new ConsultaBdsiiPorChassiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaBdsiiPorPlaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaBdsiiPorPlaca(string cpfUsuario, string senhaUsuario, string placa) {
            object[] results = this.Invoke("ConsultaBdsiiPorPlaca", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        placa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBdsiiPorPlacaAsync(string cpfUsuario, string senhaUsuario, string placa) {
            this.ConsultaBdsiiPorPlacaAsync(cpfUsuario, senhaUsuario, placa, null);
        }
        
        /// <remarks/>
        public void ConsultaBdsiiPorPlacaAsync(string cpfUsuario, string senhaUsuario, string placa, object userState) {
            if ((this.ConsultaBdsiiPorPlacaOperationCompleted == null)) {
                this.ConsultaBdsiiPorPlacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBdsiiPorPlacaOperationCompleted);
            }
            this.InvokeAsync("ConsultaBdsiiPorPlaca", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        placa}, this.ConsultaBdsiiPorPlacaOperationCompleted, userState);
        }
        
        private void OnConsultaBdsiiPorPlacaOperationCompleted(object arg) {
            if ((this.ConsultaBdsiiPorPlacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBdsiiPorPlacaCompleted(this, new ConsultaBdsiiPorPlacaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaCnhPorCpf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaCnhPorCpf(string cpfUsuario, string senhaUsuario, string val) {
            object[] results = this.Invoke("ConsultaCnhPorCpf", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        val});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaCnhPorCpfAsync(string cpfUsuario, string senhaUsuario, string val) {
            this.ConsultaCnhPorCpfAsync(cpfUsuario, senhaUsuario, val, null);
        }
        
        /// <remarks/>
        public void ConsultaCnhPorCpfAsync(string cpfUsuario, string senhaUsuario, string val, object userState) {
            if ((this.ConsultaCnhPorCpfOperationCompleted == null)) {
                this.ConsultaCnhPorCpfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaCnhPorCpfOperationCompleted);
            }
            this.InvokeAsync("ConsultaCnhPorCpf", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        val}, this.ConsultaCnhPorCpfOperationCompleted, userState);
        }
        
        private void OnConsultaCnhPorCpfOperationCompleted(object arg) {
            if ((this.ConsultaCnhPorCpfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaCnhPorCpfCompleted(this, new ConsultaCnhPorCpfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaDecodChassi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaDecodChassi(string cpfUsuario, string senhaUsuario, string val) {
            object[] results = this.Invoke("ConsultaDecodChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        val});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDecodChassiAsync(string cpfUsuario, string senhaUsuario, string val) {
            this.ConsultaDecodChassiAsync(cpfUsuario, senhaUsuario, val, null);
        }
        
        /// <remarks/>
        public void ConsultaDecodChassiAsync(string cpfUsuario, string senhaUsuario, string val, object userState) {
            if ((this.ConsultaDecodChassiOperationCompleted == null)) {
                this.ConsultaDecodChassiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDecodChassiOperationCompleted);
            }
            this.InvokeAsync("ConsultaDecodChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        val}, this.ConsultaDecodChassiOperationCompleted, userState);
        }
        
        private void OnConsultaDecodChassiOperationCompleted(object arg) {
            if ((this.ConsultaDecodChassiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDecodChassiCompleted(this, new ConsultaDecodChassiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaDpvatPorChassi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaDpvatPorChassi(string cpfUsuario, string senhaUsuario, string chassi) {
            object[] results = this.Invoke("ConsultaDpvatPorChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        chassi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDpvatPorChassiAsync(string cpfUsuario, string senhaUsuario, string chassi) {
            this.ConsultaDpvatPorChassiAsync(cpfUsuario, senhaUsuario, chassi, null);
        }
        
        /// <remarks/>
        public void ConsultaDpvatPorChassiAsync(string cpfUsuario, string senhaUsuario, string chassi, object userState) {
            if ((this.ConsultaDpvatPorChassiOperationCompleted == null)) {
                this.ConsultaDpvatPorChassiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDpvatPorChassiOperationCompleted);
            }
            this.InvokeAsync("ConsultaDpvatPorChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        chassi}, this.ConsultaDpvatPorChassiOperationCompleted, userState);
        }
        
        private void OnConsultaDpvatPorChassiOperationCompleted(object arg) {
            if ((this.ConsultaDpvatPorChassiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDpvatPorChassiCompleted(this, new ConsultaDpvatPorChassiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaDpvatPorCnpj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaDpvatPorCnpj(string cpfUsuario, string senhaUsuario, string cnpj) {
            object[] results = this.Invoke("ConsultaDpvatPorCnpj", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        cnpj});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDpvatPorCnpjAsync(string cpfUsuario, string senhaUsuario, string cnpj) {
            this.ConsultaDpvatPorCnpjAsync(cpfUsuario, senhaUsuario, cnpj, null);
        }
        
        /// <remarks/>
        public void ConsultaDpvatPorCnpjAsync(string cpfUsuario, string senhaUsuario, string cnpj, object userState) {
            if ((this.ConsultaDpvatPorCnpjOperationCompleted == null)) {
                this.ConsultaDpvatPorCnpjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDpvatPorCnpjOperationCompleted);
            }
            this.InvokeAsync("ConsultaDpvatPorCnpj", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        cnpj}, this.ConsultaDpvatPorCnpjOperationCompleted, userState);
        }
        
        private void OnConsultaDpvatPorCnpjOperationCompleted(object arg) {
            if ((this.ConsultaDpvatPorCnpjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDpvatPorCnpjCompleted(this, new ConsultaDpvatPorCnpjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaDpvatPorCpf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaDpvatPorCpf(string cpfUsuario, string senhaUsuario, string cpf) {
            object[] results = this.Invoke("ConsultaDpvatPorCpf", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        cpf});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDpvatPorCpfAsync(string cpfUsuario, string senhaUsuario, string cpf) {
            this.ConsultaDpvatPorCpfAsync(cpfUsuario, senhaUsuario, cpf, null);
        }
        
        /// <remarks/>
        public void ConsultaDpvatPorCpfAsync(string cpfUsuario, string senhaUsuario, string cpf, object userState) {
            if ((this.ConsultaDpvatPorCpfOperationCompleted == null)) {
                this.ConsultaDpvatPorCpfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDpvatPorCpfOperationCompleted);
            }
            this.InvokeAsync("ConsultaDpvatPorCpf", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        cpf}, this.ConsultaDpvatPorCpfOperationCompleted, userState);
        }
        
        private void OnConsultaDpvatPorCpfOperationCompleted(object arg) {
            if ((this.ConsultaDpvatPorCpfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDpvatPorCpfCompleted(this, new ConsultaDpvatPorCpfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaDpvatPorPlaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaDpvatPorPlaca(string cpfUsuario, string senhaUsuario, string placa) {
            object[] results = this.Invoke("ConsultaDpvatPorPlaca", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        placa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDpvatPorPlacaAsync(string cpfUsuario, string senhaUsuario, string placa) {
            this.ConsultaDpvatPorPlacaAsync(cpfUsuario, senhaUsuario, placa, null);
        }
        
        /// <remarks/>
        public void ConsultaDpvatPorPlacaAsync(string cpfUsuario, string senhaUsuario, string placa, object userState) {
            if ((this.ConsultaDpvatPorPlacaOperationCompleted == null)) {
                this.ConsultaDpvatPorPlacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDpvatPorPlacaOperationCompleted);
            }
            this.InvokeAsync("ConsultaDpvatPorPlaca", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        placa}, this.ConsultaDpvatPorPlacaOperationCompleted, userState);
        }
        
        private void OnConsultaDpvatPorPlacaOperationCompleted(object arg) {
            if ((this.ConsultaDpvatPorPlacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDpvatPorPlacaCompleted(this, new ConsultaDpvatPorPlacaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaLeilaoPorChassi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaLeilaoPorChassi(string cpfUsuario, string senhaUsuario, string chassi) {
            object[] results = this.Invoke("ConsultaLeilaoPorChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        chassi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaLeilaoPorChassiAsync(string cpfUsuario, string senhaUsuario, string chassi) {
            this.ConsultaLeilaoPorChassiAsync(cpfUsuario, senhaUsuario, chassi, null);
        }
        
        /// <remarks/>
        public void ConsultaLeilaoPorChassiAsync(string cpfUsuario, string senhaUsuario, string chassi, object userState) {
            if ((this.ConsultaLeilaoPorChassiOperationCompleted == null)) {
                this.ConsultaLeilaoPorChassiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaLeilaoPorChassiOperationCompleted);
            }
            this.InvokeAsync("ConsultaLeilaoPorChassi", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        chassi}, this.ConsultaLeilaoPorChassiOperationCompleted, userState);
        }
        
        private void OnConsultaLeilaoPorChassiOperationCompleted(object arg) {
            if ((this.ConsultaLeilaoPorChassiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaLeilaoPorChassiCompleted(this, new ConsultaLeilaoPorChassiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaLeilaoPorPlaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaLeilaoPorPlaca(string cpfUsuario, string senhaUsuario, string placa) {
            object[] results = this.Invoke("ConsultaLeilaoPorPlaca", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        placa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaLeilaoPorPlacaAsync(string cpfUsuario, string senhaUsuario, string placa) {
            this.ConsultaLeilaoPorPlacaAsync(cpfUsuario, senhaUsuario, placa, null);
        }
        
        /// <remarks/>
        public void ConsultaLeilaoPorPlacaAsync(string cpfUsuario, string senhaUsuario, string placa, object userState) {
            if ((this.ConsultaLeilaoPorPlacaOperationCompleted == null)) {
                this.ConsultaLeilaoPorPlacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaLeilaoPorPlacaOperationCompleted);
            }
            this.InvokeAsync("ConsultaLeilaoPorPlaca", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        placa}, this.ConsultaLeilaoPorPlacaOperationCompleted, userState);
        }
        
        private void OnConsultaLeilaoPorPlacaOperationCompleted(object arg) {
            if ((this.ConsultaLeilaoPorPlacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaLeilaoPorPlacaCompleted(this, new ConsultaLeilaoPorPlacaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaCpf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaCpf(string cpfUsuario, string senhaUsuario, string val) {
            object[] results = this.Invoke("ConsultaCpf", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        val});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaCpfAsync(string cpfUsuario, string senhaUsuario, string val) {
            this.ConsultaCpfAsync(cpfUsuario, senhaUsuario, val, null);
        }
        
        /// <remarks/>
        public void ConsultaCpfAsync(string cpfUsuario, string senhaUsuario, string val, object userState) {
            if ((this.ConsultaCpfOperationCompleted == null)) {
                this.ConsultaCpfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaCpfOperationCompleted);
            }
            this.InvokeAsync("ConsultaCpf", new object[] {
                        cpfUsuario,
                        senhaUsuario,
                        val}, this.ConsultaCpfOperationCompleted, userState);
        }
        
        private void OnConsultaCpfOperationCompleted(object arg) {
            if ((this.ConsultaCpfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaCpfCompleted(this, new ConsultaCpfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaBaseEstadualPorChassiCompletedEventHandler(object sender, ConsultaBaseEstadualPorChassiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBaseEstadualPorChassiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBaseEstadualPorChassiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaBaseEstadualPorPlacaCompletedEventHandler(object sender, ConsultaBaseEstadualPorPlacaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBaseEstadualPorPlacaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBaseEstadualPorPlacaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaBaseNacionalPorCaixaCambioCompletedEventHandler(object sender, ConsultaBaseNacionalPorCaixaCambioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBaseNacionalPorCaixaCambioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBaseNacionalPorCaixaCambioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaBaseNacionalPorMotorCompletedEventHandler(object sender, ConsultaBaseNacionalPorMotorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBaseNacionalPorMotorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBaseNacionalPorMotorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaBaseNacionalPorChassiCompletedEventHandler(object sender, ConsultaBaseNacionalPorChassiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBaseNacionalPorChassiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBaseNacionalPorChassiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaBaseNacionalPorPlacaCompletedEventHandler(object sender, ConsultaBaseNacionalPorPlacaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBaseNacionalPorPlacaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBaseNacionalPorPlacaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaBdrfPorChassiCompletedEventHandler(object sender, ConsultaBdrfPorChassiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBdrfPorChassiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBdrfPorChassiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaBdrfPorPlacaCompletedEventHandler(object sender, ConsultaBdrfPorPlacaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBdrfPorPlacaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBdrfPorPlacaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaBdsiiPorChassiCompletedEventHandler(object sender, ConsultaBdsiiPorChassiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBdsiiPorChassiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBdsiiPorChassiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaBdsiiPorPlacaCompletedEventHandler(object sender, ConsultaBdsiiPorPlacaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBdsiiPorPlacaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBdsiiPorPlacaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaCnhPorCpfCompletedEventHandler(object sender, ConsultaCnhPorCpfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCnhPorCpfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCnhPorCpfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaDecodChassiCompletedEventHandler(object sender, ConsultaDecodChassiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDecodChassiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDecodChassiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaDpvatPorChassiCompletedEventHandler(object sender, ConsultaDpvatPorChassiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDpvatPorChassiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDpvatPorChassiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaDpvatPorCnpjCompletedEventHandler(object sender, ConsultaDpvatPorCnpjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDpvatPorCnpjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDpvatPorCnpjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaDpvatPorCpfCompletedEventHandler(object sender, ConsultaDpvatPorCpfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDpvatPorCpfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDpvatPorCpfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaDpvatPorPlacaCompletedEventHandler(object sender, ConsultaDpvatPorPlacaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDpvatPorPlacaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDpvatPorPlacaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaLeilaoPorChassiCompletedEventHandler(object sender, ConsultaLeilaoPorChassiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaLeilaoPorChassiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaLeilaoPorChassiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaLeilaoPorPlacaCompletedEventHandler(object sender, ConsultaLeilaoPorPlacaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaLeilaoPorPlacaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaLeilaoPorPlacaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ConsultaCpfCompletedEventHandler(object sender, ConsultaCpfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCpfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCpfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591