//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webServiceCheckOk.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webservice.credify.com.br/wscredify.php")]
        public string webServiceCheckOk_WsCredify_server_consulta {
            get {
                return ((string)(this["webServiceCheckOk_WsCredify_server_consulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.checkauto.com.br/ws20v2/WebService1.asmx")]
        public string webServiceCheckOk_WsCheckAuto_WebService1 {
            get {
                return ((string)(this["webServiceCheckOk_WsCheckAuto_WebService1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webservices.absolutasolucoes.com.br/absoluta/clsLeilao.asmx")]
        public string webServiceCheckOk_WsAbsolutaSolucoes_clsLeilao {
            get {
                return ((string)(this["webServiceCheckOk_WsAbsolutaSolucoes_clsLeilao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wsar.autorisco.com.br/bdvl/services/Bdvl/bdvl.asmx")]
        public string webServiceCheckOk_WsAutoRisco_Bdvl {
            get {
                return ((string)(this["webServiceCheckOk_WsAutoRisco_Bdvl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.carsys.com.br/consulta/ws.asmx")]
        public string webServiceCheckOk_WsCarsys_ws {
            get {
                return ((string)(this["webServiceCheckOk_WsCarsys_ws"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webservice.credhost.com.br/VeicularNew.asmx")]
        public string webServiceCheckOk_WsSeape_VeicularNew {
            get {
                return ((string)(this["webServiceCheckOk_WsSeape_VeicularNew"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://177.139.253.143:8080/ConsultasWS/services/Consulta.ConsultaHttpSoap11Endpo" +
            "int/")]
        public string webServiceCheckOk_WsTdi_Consulta {
            get {
                return ((string)(this["webServiceCheckOk_WsTdi_Consulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://206.222.9.194/WServConsultasVeiculos/WServCons.asmx")]
        public string webServiceCheckOk_WsSinaliza_ConsultasVeiculos {
            get {
                return ((string)(this["webServiceCheckOk_WsSinaliza_ConsultasVeiculos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.checkpro.com.br/service.asmx")]
        public string webServiceCheckOk_WsCheckPro_Service {
            get {
                return ((string)(this["webServiceCheckOk_WsCheckPro_Service"]));
            }
        }
    }
}
