//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace webServiceCheckOk.WsAutoRisco {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BdvlSoap", Namespace="http://tempuri.org/")]
    public partial class Bdvl : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback pesquisarPlacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback pesquisarChassiOperationCompleted;
        
        private System.Threading.SendOrPostCallback pesquisarRestrDebitosSPOperationCompleted;
        
        private System.Threading.SendOrPostCallback pesquisarRestrDebitosOutrasUFsOperationCompleted;
        
        private System.Threading.SendOrPostCallback pesquisarDecodificadorChassi2OperationCompleted;
        
        private System.Threading.SendOrPostCallback pesquisarDecodficadorChassiOperationCompleted;
        
        private System.Threading.SendOrPostCallback PesquisaSinistroOperationCompleted;
        
        private System.Threading.SendOrPostCallback pesquisaSinistro2OperationCompleted;
        
        private System.Threading.SendOrPostCallback PesquisaLeilaoSinistroOperationCompleted;
        
        private System.Threading.SendOrPostCallback pesquisarPlacaChassiXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback pesquisarPlacaChassiOperationCompleted;
        
        private System.Threading.SendOrPostCallback pesquisarPlacaChassiIndiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Bdvl() {
            this.Url = global::webServiceCheckOk.Properties.Settings.Default.webServiceCheckOk_WsAutoRisco_Bdvl;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event pesquisarPlacaCompletedEventHandler pesquisarPlacaCompleted;
        
        /// <remarks/>
        public event pesquisarChassiCompletedEventHandler pesquisarChassiCompleted;
        
        /// <remarks/>
        public event pesquisarRestrDebitosSPCompletedEventHandler pesquisarRestrDebitosSPCompleted;
        
        /// <remarks/>
        public event pesquisarRestrDebitosOutrasUFsCompletedEventHandler pesquisarRestrDebitosOutrasUFsCompleted;
        
        /// <remarks/>
        public event pesquisarDecodificadorChassi2CompletedEventHandler pesquisarDecodificadorChassi2Completed;
        
        /// <remarks/>
        public event pesquisarDecodficadorChassiCompletedEventHandler pesquisarDecodficadorChassiCompleted;
        
        /// <remarks/>
        public event PesquisaSinistroCompletedEventHandler PesquisaSinistroCompleted;
        
        /// <remarks/>
        public event pesquisaSinistro2CompletedEventHandler pesquisaSinistro2Completed;
        
        /// <remarks/>
        public event PesquisaLeilaoSinistroCompletedEventHandler PesquisaLeilaoSinistroCompleted;
        
        /// <remarks/>
        public event pesquisarPlacaChassiXMLCompletedEventHandler pesquisarPlacaChassiXMLCompleted;
        
        /// <remarks/>
        public event pesquisarPlacaChassiCompletedEventHandler pesquisarPlacaChassiCompleted;
        
        /// <remarks/>
        public event pesquisarPlacaChassiIndiceCompletedEventHandler pesquisarPlacaChassiIndiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pesquisarPlaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string pesquisarPlaca(string login, string password, string placa) {
            object[] results = this.Invoke("pesquisarPlaca", new object[] {
                        login,
                        password,
                        placa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pesquisarPlacaAsync(string login, string password, string placa) {
            this.pesquisarPlacaAsync(login, password, placa, null);
        }
        
        /// <remarks/>
        public void pesquisarPlacaAsync(string login, string password, string placa, object userState) {
            if ((this.pesquisarPlacaOperationCompleted == null)) {
                this.pesquisarPlacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpesquisarPlacaOperationCompleted);
            }
            this.InvokeAsync("pesquisarPlaca", new object[] {
                        login,
                        password,
                        placa}, this.pesquisarPlacaOperationCompleted, userState);
        }
        
        private void OnpesquisarPlacaOperationCompleted(object arg) {
            if ((this.pesquisarPlacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pesquisarPlacaCompleted(this, new pesquisarPlacaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pesquisarChassi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string pesquisarChassi(string login, string password, string chassi) {
            object[] results = this.Invoke("pesquisarChassi", new object[] {
                        login,
                        password,
                        chassi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pesquisarChassiAsync(string login, string password, string chassi) {
            this.pesquisarChassiAsync(login, password, chassi, null);
        }
        
        /// <remarks/>
        public void pesquisarChassiAsync(string login, string password, string chassi, object userState) {
            if ((this.pesquisarChassiOperationCompleted == null)) {
                this.pesquisarChassiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpesquisarChassiOperationCompleted);
            }
            this.InvokeAsync("pesquisarChassi", new object[] {
                        login,
                        password,
                        chassi}, this.pesquisarChassiOperationCompleted, userState);
        }
        
        private void OnpesquisarChassiOperationCompleted(object arg) {
            if ((this.pesquisarChassiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pesquisarChassiCompleted(this, new pesquisarChassiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pesquisarRestrDebitosSP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode pesquisarRestrDebitosSP(string login, string password, string strPlaca, string strchassi) {
            object[] results = this.Invoke("pesquisarRestrDebitosSP", new object[] {
                        login,
                        password,
                        strPlaca,
                        strchassi});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void pesquisarRestrDebitosSPAsync(string login, string password, string strPlaca, string strchassi) {
            this.pesquisarRestrDebitosSPAsync(login, password, strPlaca, strchassi, null);
        }
        
        /// <remarks/>
        public void pesquisarRestrDebitosSPAsync(string login, string password, string strPlaca, string strchassi, object userState) {
            if ((this.pesquisarRestrDebitosSPOperationCompleted == null)) {
                this.pesquisarRestrDebitosSPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpesquisarRestrDebitosSPOperationCompleted);
            }
            this.InvokeAsync("pesquisarRestrDebitosSP", new object[] {
                        login,
                        password,
                        strPlaca,
                        strchassi}, this.pesquisarRestrDebitosSPOperationCompleted, userState);
        }
        
        private void OnpesquisarRestrDebitosSPOperationCompleted(object arg) {
            if ((this.pesquisarRestrDebitosSPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pesquisarRestrDebitosSPCompleted(this, new pesquisarRestrDebitosSPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pesquisarRestrDebitosOutrasUFs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode pesquisarRestrDebitosOutrasUFs(string login, string password, string strPlaca, string strchassi, string strUF) {
            object[] results = this.Invoke("pesquisarRestrDebitosOutrasUFs", new object[] {
                        login,
                        password,
                        strPlaca,
                        strchassi,
                        strUF});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void pesquisarRestrDebitosOutrasUFsAsync(string login, string password, string strPlaca, string strchassi, string strUF) {
            this.pesquisarRestrDebitosOutrasUFsAsync(login, password, strPlaca, strchassi, strUF, null);
        }
        
        /// <remarks/>
        public void pesquisarRestrDebitosOutrasUFsAsync(string login, string password, string strPlaca, string strchassi, string strUF, object userState) {
            if ((this.pesquisarRestrDebitosOutrasUFsOperationCompleted == null)) {
                this.pesquisarRestrDebitosOutrasUFsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpesquisarRestrDebitosOutrasUFsOperationCompleted);
            }
            this.InvokeAsync("pesquisarRestrDebitosOutrasUFs", new object[] {
                        login,
                        password,
                        strPlaca,
                        strchassi,
                        strUF}, this.pesquisarRestrDebitosOutrasUFsOperationCompleted, userState);
        }
        
        private void OnpesquisarRestrDebitosOutrasUFsOperationCompleted(object arg) {
            if ((this.pesquisarRestrDebitosOutrasUFsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pesquisarRestrDebitosOutrasUFsCompleted(this, new pesquisarRestrDebitosOutrasUFsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pesquisarDecodificadorChassi2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode pesquisarDecodificadorChassi2(string login, string password, string strchassi) {
            object[] results = this.Invoke("pesquisarDecodificadorChassi2", new object[] {
                        login,
                        password,
                        strchassi});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void pesquisarDecodificadorChassi2Async(string login, string password, string strchassi) {
            this.pesquisarDecodificadorChassi2Async(login, password, strchassi, null);
        }
        
        /// <remarks/>
        public void pesquisarDecodificadorChassi2Async(string login, string password, string strchassi, object userState) {
            if ((this.pesquisarDecodificadorChassi2OperationCompleted == null)) {
                this.pesquisarDecodificadorChassi2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnpesquisarDecodificadorChassi2OperationCompleted);
            }
            this.InvokeAsync("pesquisarDecodificadorChassi2", new object[] {
                        login,
                        password,
                        strchassi}, this.pesquisarDecodificadorChassi2OperationCompleted, userState);
        }
        
        private void OnpesquisarDecodificadorChassi2OperationCompleted(object arg) {
            if ((this.pesquisarDecodificadorChassi2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pesquisarDecodificadorChassi2Completed(this, new pesquisarDecodificadorChassi2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pesquisarDecodficadorChassi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string pesquisarDecodficadorChassi(string login, string password, string strchassi) {
            object[] results = this.Invoke("pesquisarDecodficadorChassi", new object[] {
                        login,
                        password,
                        strchassi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pesquisarDecodficadorChassiAsync(string login, string password, string strchassi) {
            this.pesquisarDecodficadorChassiAsync(login, password, strchassi, null);
        }
        
        /// <remarks/>
        public void pesquisarDecodficadorChassiAsync(string login, string password, string strchassi, object userState) {
            if ((this.pesquisarDecodficadorChassiOperationCompleted == null)) {
                this.pesquisarDecodficadorChassiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpesquisarDecodficadorChassiOperationCompleted);
            }
            this.InvokeAsync("pesquisarDecodficadorChassi", new object[] {
                        login,
                        password,
                        strchassi}, this.pesquisarDecodficadorChassiOperationCompleted, userState);
        }
        
        private void OnpesquisarDecodficadorChassiOperationCompleted(object arg) {
            if ((this.pesquisarDecodficadorChassiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pesquisarDecodficadorChassiCompleted(this, new pesquisarDecodficadorChassiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PesquisaSinistro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode PesquisaSinistro(string login, string password, string placa, string chassi) {
            object[] results = this.Invoke("PesquisaSinistro", new object[] {
                        login,
                        password,
                        placa,
                        chassi});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void PesquisaSinistroAsync(string login, string password, string placa, string chassi) {
            this.PesquisaSinistroAsync(login, password, placa, chassi, null);
        }
        
        /// <remarks/>
        public void PesquisaSinistroAsync(string login, string password, string placa, string chassi, object userState) {
            if ((this.PesquisaSinistroOperationCompleted == null)) {
                this.PesquisaSinistroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPesquisaSinistroOperationCompleted);
            }
            this.InvokeAsync("PesquisaSinistro", new object[] {
                        login,
                        password,
                        placa,
                        chassi}, this.PesquisaSinistroOperationCompleted, userState);
        }
        
        private void OnPesquisaSinistroOperationCompleted(object arg) {
            if ((this.PesquisaSinistroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PesquisaSinistroCompleted(this, new PesquisaSinistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pesquisaSinistro2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode pesquisaSinistro2(string login, string password, string strPlaca, string strchassi) {
            object[] results = this.Invoke("pesquisaSinistro2", new object[] {
                        login,
                        password,
                        strPlaca,
                        strchassi});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void pesquisaSinistro2Async(string login, string password, string strPlaca, string strchassi) {
            this.pesquisaSinistro2Async(login, password, strPlaca, strchassi, null);
        }
        
        /// <remarks/>
        public void pesquisaSinistro2Async(string login, string password, string strPlaca, string strchassi, object userState) {
            if ((this.pesquisaSinistro2OperationCompleted == null)) {
                this.pesquisaSinistro2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnpesquisaSinistro2OperationCompleted);
            }
            this.InvokeAsync("pesquisaSinistro2", new object[] {
                        login,
                        password,
                        strPlaca,
                        strchassi}, this.pesquisaSinistro2OperationCompleted, userState);
        }
        
        private void OnpesquisaSinistro2OperationCompleted(object arg) {
            if ((this.pesquisaSinistro2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pesquisaSinistro2Completed(this, new pesquisaSinistro2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PesquisaLeilaoSinistro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode PesquisaLeilaoSinistro(string login, string password, string placa, string chassi) {
            object[] results = this.Invoke("PesquisaLeilaoSinistro", new object[] {
                        login,
                        password,
                        placa,
                        chassi});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void PesquisaLeilaoSinistroAsync(string login, string password, string placa, string chassi) {
            this.PesquisaLeilaoSinistroAsync(login, password, placa, chassi, null);
        }
        
        /// <remarks/>
        public void PesquisaLeilaoSinistroAsync(string login, string password, string placa, string chassi, object userState) {
            if ((this.PesquisaLeilaoSinistroOperationCompleted == null)) {
                this.PesquisaLeilaoSinistroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPesquisaLeilaoSinistroOperationCompleted);
            }
            this.InvokeAsync("PesquisaLeilaoSinistro", new object[] {
                        login,
                        password,
                        placa,
                        chassi}, this.PesquisaLeilaoSinistroOperationCompleted, userState);
        }
        
        private void OnPesquisaLeilaoSinistroOperationCompleted(object arg) {
            if ((this.PesquisaLeilaoSinistroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PesquisaLeilaoSinistroCompleted(this, new PesquisaLeilaoSinistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pesquisarPlacaChassiXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode pesquisarPlacaChassiXML(string login, string password, string placa, string chassi) {
            object[] results = this.Invoke("pesquisarPlacaChassiXML", new object[] {
                        login,
                        password,
                        placa,
                        chassi});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void pesquisarPlacaChassiXMLAsync(string login, string password, string placa, string chassi) {
            this.pesquisarPlacaChassiXMLAsync(login, password, placa, chassi, null);
        }
        
        /// <remarks/>
        public void pesquisarPlacaChassiXMLAsync(string login, string password, string placa, string chassi, object userState) {
            if ((this.pesquisarPlacaChassiXMLOperationCompleted == null)) {
                this.pesquisarPlacaChassiXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpesquisarPlacaChassiXMLOperationCompleted);
            }
            this.InvokeAsync("pesquisarPlacaChassiXML", new object[] {
                        login,
                        password,
                        placa,
                        chassi}, this.pesquisarPlacaChassiXMLOperationCompleted, userState);
        }
        
        private void OnpesquisarPlacaChassiXMLOperationCompleted(object arg) {
            if ((this.pesquisarPlacaChassiXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pesquisarPlacaChassiXMLCompleted(this, new pesquisarPlacaChassiXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pesquisarPlacaChassi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string pesquisarPlacaChassi(string login, string password, string placa, string chassi) {
            object[] results = this.Invoke("pesquisarPlacaChassi", new object[] {
                        login,
                        password,
                        placa,
                        chassi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pesquisarPlacaChassiAsync(string login, string password, string placa, string chassi) {
            this.pesquisarPlacaChassiAsync(login, password, placa, chassi, null);
        }
        
        /// <remarks/>
        public void pesquisarPlacaChassiAsync(string login, string password, string placa, string chassi, object userState) {
            if ((this.pesquisarPlacaChassiOperationCompleted == null)) {
                this.pesquisarPlacaChassiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpesquisarPlacaChassiOperationCompleted);
            }
            this.InvokeAsync("pesquisarPlacaChassi", new object[] {
                        login,
                        password,
                        placa,
                        chassi}, this.pesquisarPlacaChassiOperationCompleted, userState);
        }
        
        private void OnpesquisarPlacaChassiOperationCompleted(object arg) {
            if ((this.pesquisarPlacaChassiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pesquisarPlacaChassiCompleted(this, new pesquisarPlacaChassiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pesquisarPlacaChassiIndice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string pesquisarPlacaChassiIndice(string login, string password, string placa, string chassi) {
            object[] results = this.Invoke("pesquisarPlacaChassiIndice", new object[] {
                        login,
                        password,
                        placa,
                        chassi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pesquisarPlacaChassiIndiceAsync(string login, string password, string placa, string chassi) {
            this.pesquisarPlacaChassiIndiceAsync(login, password, placa, chassi, null);
        }
        
        /// <remarks/>
        public void pesquisarPlacaChassiIndiceAsync(string login, string password, string placa, string chassi, object userState) {
            if ((this.pesquisarPlacaChassiIndiceOperationCompleted == null)) {
                this.pesquisarPlacaChassiIndiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpesquisarPlacaChassiIndiceOperationCompleted);
            }
            this.InvokeAsync("pesquisarPlacaChassiIndice", new object[] {
                        login,
                        password,
                        placa,
                        chassi}, this.pesquisarPlacaChassiIndiceOperationCompleted, userState);
        }
        
        private void OnpesquisarPlacaChassiIndiceOperationCompleted(object arg) {
            if ((this.pesquisarPlacaChassiIndiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pesquisarPlacaChassiIndiceCompleted(this, new pesquisarPlacaChassiIndiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void pesquisarPlacaCompletedEventHandler(object sender, pesquisarPlacaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pesquisarPlacaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pesquisarPlacaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void pesquisarChassiCompletedEventHandler(object sender, pesquisarChassiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pesquisarChassiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pesquisarChassiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void pesquisarRestrDebitosSPCompletedEventHandler(object sender, pesquisarRestrDebitosSPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pesquisarRestrDebitosSPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pesquisarRestrDebitosSPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void pesquisarRestrDebitosOutrasUFsCompletedEventHandler(object sender, pesquisarRestrDebitosOutrasUFsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pesquisarRestrDebitosOutrasUFsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pesquisarRestrDebitosOutrasUFsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void pesquisarDecodificadorChassi2CompletedEventHandler(object sender, pesquisarDecodificadorChassi2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pesquisarDecodificadorChassi2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pesquisarDecodificadorChassi2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void pesquisarDecodficadorChassiCompletedEventHandler(object sender, pesquisarDecodficadorChassiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pesquisarDecodficadorChassiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pesquisarDecodficadorChassiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void PesquisaSinistroCompletedEventHandler(object sender, PesquisaSinistroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PesquisaSinistroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PesquisaSinistroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void pesquisaSinistro2CompletedEventHandler(object sender, pesquisaSinistro2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pesquisaSinistro2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pesquisaSinistro2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void PesquisaLeilaoSinistroCompletedEventHandler(object sender, PesquisaLeilaoSinistroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PesquisaLeilaoSinistroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PesquisaLeilaoSinistroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void pesquisarPlacaChassiXMLCompletedEventHandler(object sender, pesquisarPlacaChassiXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pesquisarPlacaChassiXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pesquisarPlacaChassiXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void pesquisarPlacaChassiCompletedEventHandler(object sender, pesquisarPlacaChassiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pesquisarPlacaChassiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pesquisarPlacaChassiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void pesquisarPlacaChassiIndiceCompletedEventHandler(object sender, pesquisarPlacaChassiIndiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pesquisarPlacaChassiIndiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pesquisarPlacaChassiIndiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591