//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace webServiceCheckOk.WsTdi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultaSoap11Binding", Namespace="http://ws")]
    public partial class Consulta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaRfOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaGravameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Consulta() {
            this.Url = global::webServiceCheckOk.Properties.Settings.Default.webServiceCheckOk_WsTdi_Consulta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaRfCompletedEventHandler consultaRfCompleted;
        
        /// <remarks/>
        public event consultaGravameCompletedEventHandler consultaGravameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:consultaRf", RequestNamespace="http://ws", ResponseNamespace="http://ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public RfDenatran consultaRf([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string senha, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string placa) {
            object[] results = this.Invoke("consultaRf", new object[] {
                        login,
                        senha,
                        placa});
            return ((RfDenatran)(results[0]));
        }
        
        /// <remarks/>
        public void consultaRfAsync(string login, string senha, string placa) {
            this.consultaRfAsync(login, senha, placa, null);
        }
        
        /// <remarks/>
        public void consultaRfAsync(string login, string senha, string placa, object userState) {
            if ((this.consultaRfOperationCompleted == null)) {
                this.consultaRfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaRfOperationCompleted);
            }
            this.InvokeAsync("consultaRf", new object[] {
                        login,
                        senha,
                        placa}, this.consultaRfOperationCompleted, userState);
        }
        
        private void OnconsultaRfOperationCompleted(object arg) {
            if ((this.consultaRfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaRfCompleted(this, new consultaRfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:consultaGravame", RequestNamespace="http://ws", ResponseNamespace="http://ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Gravame consultaGravame([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string senha, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string chassi) {
            object[] results = this.Invoke("consultaGravame", new object[] {
                        login,
                        senha,
                        chassi});
            return ((Gravame)(results[0]));
        }
        
        /// <remarks/>
        public void consultaGravameAsync(string login, string senha, string chassi) {
            this.consultaGravameAsync(login, senha, chassi, null);
        }
        
        /// <remarks/>
        public void consultaGravameAsync(string login, string senha, string chassi, object userState) {
            if ((this.consultaGravameOperationCompleted == null)) {
                this.consultaGravameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaGravameOperationCompleted);
            }
            this.InvokeAsync("consultaGravame", new object[] {
                        login,
                        senha,
                        chassi}, this.consultaGravameOperationCompleted, userState);
        }
        
        private void OnconsultaGravameOperationCompleted(object arg) {
            if ((this.consultaGravameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaGravameCompleted(this, new consultaGravameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rfdenatran.w3it.com.br/xsd")]
    public partial class RfDenatran {
        
        private string anoField;
        
        private string anoModeloField;
        
        private string chassiField;
        
        private string codigoRetornoField;
        
        private string codigoSituacaoField;
        
        private string corField;
        
        private string dataField;
        
        private string marcaField;
        
        private string mensagemRetornoField;
        
        private string modeloField;
        
        private string municipioField;
        
        private string placaField;
        
        private string situacaoField;
        
        private string ufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string anoModelo {
            get {
                return this.anoModeloField;
            }
            set {
                this.anoModeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codigoSituacao {
            get {
                return this.codigoSituacaoField;
            }
            set {
                this.codigoSituacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cor {
            get {
                return this.corField;
            }
            set {
                this.corField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gravame.w3it.com.br/xsd")]
    public partial class Gravame {
        
        private string chassiField;
        
        private string gravameanofabricacaoField;
        
        private string gravameanomodeloField;
        
        private string gravamecnpjagenteField;
        
        private string gravamecodigoagenteField;
        
        private string gravamedatastatusField;
        
        private string gravamedescricaostatusField;
        
        private string gravamenomeagenteField;
        
        private string gravamenumerogravameField;
        
        private string gravameplacaField;
        
        private string gravamestatusveiculoField;
        
        private string gravameufgravameField;
        
        private string gravameufplacaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gravameanofabricacao {
            get {
                return this.gravameanofabricacaoField;
            }
            set {
                this.gravameanofabricacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gravameanomodelo {
            get {
                return this.gravameanomodeloField;
            }
            set {
                this.gravameanomodeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gravamecnpjagente {
            get {
                return this.gravamecnpjagenteField;
            }
            set {
                this.gravamecnpjagenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gravamecodigoagente {
            get {
                return this.gravamecodigoagenteField;
            }
            set {
                this.gravamecodigoagenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gravamedatastatus {
            get {
                return this.gravamedatastatusField;
            }
            set {
                this.gravamedatastatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gravamedescricaostatus {
            get {
                return this.gravamedescricaostatusField;
            }
            set {
                this.gravamedescricaostatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gravamenomeagente {
            get {
                return this.gravamenomeagenteField;
            }
            set {
                this.gravamenomeagenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gravamenumerogravame {
            get {
                return this.gravamenumerogravameField;
            }
            set {
                this.gravamenumerogravameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gravameplaca {
            get {
                return this.gravameplacaField;
            }
            set {
                this.gravameplacaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gravamestatusveiculo {
            get {
                return this.gravamestatusveiculoField;
            }
            set {
                this.gravamestatusveiculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gravameufgravame {
            get {
                return this.gravameufgravameField;
            }
            set {
                this.gravameufgravameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gravameufplaca {
            get {
                return this.gravameufplacaField;
            }
            set {
                this.gravameufplacaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void consultaRfCompletedEventHandler(object sender, consultaRfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaRfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaRfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RfDenatran Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RfDenatran)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void consultaGravameCompletedEventHandler(object sender, consultaGravameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaGravameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaGravameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Gravame Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Gravame)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591