//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webServiceCheckOk.WsTecnobank {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsTecnobank.IeDecodificacao")]
    public interface IeDecodificacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/DecodificarChassi", ReplyAction="http://tempuri.org/IeDecodificacao/DecodificarChassiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        webServiceCheckOk.WsTecnobank.ENTModeloVeiculo DecodificarChassi(string pastrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/DecodificarChassi", ReplyAction="http://tempuri.org/IeDecodificacao/DecodificarChassiResponse")]
        System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> DecodificarChassiAsync(string pastrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/DecodificarPlaca", ReplyAction="http://tempuri.org/IeDecodificacao/DecodificarPlacaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        webServiceCheckOk.WsTecnobank.ENTModeloVeiculo DecodificarPlaca(string pastrPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/DecodificarPlaca", ReplyAction="http://tempuri.org/IeDecodificacao/DecodificarPlacaResponse")]
        System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> DecodificarPlacaAsync(string pastrPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/PrecificadorChassiI", ReplyAction="http://tempuri.org/IeDecodificacao/PrecificadorChassiIResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        webServiceCheckOk.WsTecnobank.ENTModeloVeiculo PrecificadorChassiI(string pastrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/PrecificadorChassiI", ReplyAction="http://tempuri.org/IeDecodificacao/PrecificadorChassiIResponse")]
        System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> PrecificadorChassiIAsync(string pastrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/PrecificadorPlacaI", ReplyAction="http://tempuri.org/IeDecodificacao/PrecificadorPlacaIResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        webServiceCheckOk.WsTecnobank.ENTModeloVeiculo PrecificadorPlacaI(string pastrPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/PrecificadorPlacaI", ReplyAction="http://tempuri.org/IeDecodificacao/PrecificadorPlacaIResponse")]
        System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> PrecificadorPlacaIAsync(string pastrPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/PrecificadorChassiII", ReplyAction="http://tempuri.org/IeDecodificacao/PrecificadorChassiIIResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        webServiceCheckOk.WsTecnobank.ENTModeloVeiculo PrecificadorChassiII(string pastrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/PrecificadorChassiII", ReplyAction="http://tempuri.org/IeDecodificacao/PrecificadorChassiIIResponse")]
        System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> PrecificadorChassiIIAsync(string pastrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/PrecificadorPlacaII", ReplyAction="http://tempuri.org/IeDecodificacao/PrecificadorPlacaIIResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        webServiceCheckOk.WsTecnobank.ENTModeloVeiculo PrecificadorPlacaII(string pastrPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/PrecificadorPlacaII", ReplyAction="http://tempuri.org/IeDecodificacao/PrecificadorPlacaIIResponse")]
        System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> PrecificadorPlacaIIAsync(string pastrPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/DecodificadorPrecificadoresChassi", ReplyAction="http://tempuri.org/IeDecodificacao/DecodificadorPrecificadoresChassiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        webServiceCheckOk.WsTecnobank.ENTModeloVeiculo DecodificadorPrecificadoresChassi(string pastrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/DecodificadorPrecificadoresChassi", ReplyAction="http://tempuri.org/IeDecodificacao/DecodificadorPrecificadoresChassiResponse")]
        System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> DecodificadorPrecificadoresChassiAsync(string pastrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/DecodificadorPrecificadoresPlaca", ReplyAction="http://tempuri.org/IeDecodificacao/DecodificadorPrecificadoresPlacaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        webServiceCheckOk.WsTecnobank.ENTModeloVeiculo DecodificadorPrecificadoresPlaca(string pastrPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeDecodificacao/DecodificadorPrecificadoresPlaca", ReplyAction="http://tempuri.org/IeDecodificacao/DecodificadorPrecificadoresPlacaResponse")]
        System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> DecodificadorPrecificadoresPlacaAsync(string pastrPlaca);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloVeiculoPlaca))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloVeiculoValidador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloVeiculoValidadorPlaca))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENTModeloVeiculo : ENTModeloDecodificacao {
        
        private System.Nullable<int> cdRetornoField;
        
        private string dsRetornoField;
        
        private string dsChassiTratadoField;
        
        private ENTModeloPrecificadorI[] modelosPrecificadorIField;
        
        private ENTModeloPrecificadorII[] modelosPrecificadorIIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> CdRetorno {
            get {
                return this.cdRetornoField;
            }
            set {
                this.cdRetornoField = value;
                this.RaisePropertyChanged("CdRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DsRetorno {
            get {
                return this.dsRetornoField;
            }
            set {
                this.dsRetornoField = value;
                this.RaisePropertyChanged("DsRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DsChassiTratado {
            get {
                return this.dsChassiTratadoField;
            }
            set {
                this.dsChassiTratadoField = value;
                this.RaisePropertyChanged("DsChassiTratado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public ENTModeloPrecificadorI[] ModelosPrecificadorI {
            get {
                return this.modelosPrecificadorIField;
            }
            set {
                this.modelosPrecificadorIField = value;
                this.RaisePropertyChanged("ModelosPrecificadorI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public ENTModeloPrecificadorII[] ModelosPrecificadorII {
            get {
                return this.modelosPrecificadorIIField;
            }
            set {
                this.modelosPrecificadorIIField = value;
                this.RaisePropertyChanged("ModelosPrecificadorII");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENTModeloPrecificadorI : BaseEntity {
        
        private string dsCodigoField;
        
        private string dsMarcaField;
        
        private string dsModeloField;
        
        private string dsCombustivelField;
        
        private ENTModeloPrecificadorIAno[] modeloPrecificadorIAnosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DsCodigo {
            get {
                return this.dsCodigoField;
            }
            set {
                this.dsCodigoField = value;
                this.RaisePropertyChanged("DsCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DsMarca {
            get {
                return this.dsMarcaField;
            }
            set {
                this.dsMarcaField = value;
                this.RaisePropertyChanged("DsMarca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DsModelo {
            get {
                return this.dsModeloField;
            }
            set {
                this.dsModeloField = value;
                this.RaisePropertyChanged("DsModelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DsCombustivel {
            get {
                return this.dsCombustivelField;
            }
            set {
                this.dsCombustivelField = value;
                this.RaisePropertyChanged("DsCombustivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ModeloPrecificadorIAnos", Order=4)]
        public ENTModeloPrecificadorIAno[] ModeloPrecificadorIAnos {
            get {
                return this.modeloPrecificadorIAnosField;
            }
            set {
                this.modeloPrecificadorIAnosField = value;
                this.RaisePropertyChanged("ModeloPrecificadorIAnos");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENTModeloPrecificadorIAno : BaseEntity {
        
        private ENTModeloPrecificadorIValor[] modeloPrecificadorIValorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ModeloPrecificadorIValor", Order=0)]
        public ENTModeloPrecificadorIValor[] ModeloPrecificadorIValor {
            get {
                return this.modeloPrecificadorIValorField;
            }
            set {
                this.modeloPrecificadorIValorField = value;
                this.RaisePropertyChanged("ModeloPrecificadorIValor");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENTModeloPrecificadorIValor : BaseEntity {
        
        private System.Nullable<int> nuValorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> NuValor {
            get {
                return this.nuValorField;
            }
            set {
                this.nuValorField = value;
                this.RaisePropertyChanged("NuValor");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloPrecificadorIIValor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloPrecificadorIIAno))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloPrecificadorII))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloPrecificadorIValor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloPrecificadorIAno))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloPrecificadorI))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloDecodificacao))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloVeiculo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloVeiculoPlaca))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloVeiculoValidador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloVeiculoValidadorPlaca))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENTModeloPrecificadorIIValor : BaseEntity {
        
        private System.Nullable<int> nuValorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> NuValor {
            get {
                return this.nuValorField;
            }
            set {
                this.nuValorField = value;
                this.RaisePropertyChanged("NuValor");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENTModeloPrecificadorIIAno : BaseEntity {
        
        private ENTModeloPrecificadorIIValor[] modeloPrecificadorIIValorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ModeloPrecificadorIIValor", Order=0)]
        public ENTModeloPrecificadorIIValor[] ModeloPrecificadorIIValor {
            get {
                return this.modeloPrecificadorIIValorField;
            }
            set {
                this.modeloPrecificadorIIValorField = value;
                this.RaisePropertyChanged("ModeloPrecificadorIIValor");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENTModeloPrecificadorII : BaseEntity {
        
        private string dsCodigoField;
        
        private string dsMarcaField;
        
        private string dsModeloField;
        
        private string dsVersaoField;
        
        private string dsCombustivelField;
        
        private ENTModeloPrecificadorIIAno[] modeloPrecificadorIIAnosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DsCodigo {
            get {
                return this.dsCodigoField;
            }
            set {
                this.dsCodigoField = value;
                this.RaisePropertyChanged("DsCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DsMarca {
            get {
                return this.dsMarcaField;
            }
            set {
                this.dsMarcaField = value;
                this.RaisePropertyChanged("DsMarca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DsModelo {
            get {
                return this.dsModeloField;
            }
            set {
                this.dsModeloField = value;
                this.RaisePropertyChanged("DsModelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DsVersao {
            get {
                return this.dsVersaoField;
            }
            set {
                this.dsVersaoField = value;
                this.RaisePropertyChanged("DsVersao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DsCombustivel {
            get {
                return this.dsCombustivelField;
            }
            set {
                this.dsCombustivelField = value;
                this.RaisePropertyChanged("DsCombustivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ModeloPrecificadorIIAnos", Order=5)]
        public ENTModeloPrecificadorIIAno[] ModeloPrecificadorIIAnos {
            get {
                return this.modeloPrecificadorIIAnosField;
            }
            set {
                this.modeloPrecificadorIIAnosField = value;
                this.RaisePropertyChanged("ModeloPrecificadorIIAnos");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloVeiculo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloVeiculoPlaca))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloVeiculoValidador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloVeiculoValidadorPlaca))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENTModeloDecodificacao : BaseEntity {
        
        private string dsChassiField;
        
        private string dsOrigemField;
        
        private string dsRegiaoField;
        
        private string dsPaisField;
        
        private string dsCategoriaField;
        
        private string dsMarcaField;
        
        private string dsModeloField;
        
        private System.Nullable<int> nuAnoField;
        
        private string dsCarroceriaField;
        
        private string dsVersaoField;
        
        private string dsMotorField;
        
        private string dsCombustivelField;
        
        private string dsLocalFabricacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DsChassi {
            get {
                return this.dsChassiField;
            }
            set {
                this.dsChassiField = value;
                this.RaisePropertyChanged("DsChassi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DsOrigem {
            get {
                return this.dsOrigemField;
            }
            set {
                this.dsOrigemField = value;
                this.RaisePropertyChanged("DsOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DsRegiao {
            get {
                return this.dsRegiaoField;
            }
            set {
                this.dsRegiaoField = value;
                this.RaisePropertyChanged("DsRegiao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DsPais {
            get {
                return this.dsPaisField;
            }
            set {
                this.dsPaisField = value;
                this.RaisePropertyChanged("DsPais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DsCategoria {
            get {
                return this.dsCategoriaField;
            }
            set {
                this.dsCategoriaField = value;
                this.RaisePropertyChanged("DsCategoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DsMarca {
            get {
                return this.dsMarcaField;
            }
            set {
                this.dsMarcaField = value;
                this.RaisePropertyChanged("DsMarca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DsModelo {
            get {
                return this.dsModeloField;
            }
            set {
                this.dsModeloField = value;
                this.RaisePropertyChanged("DsModelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> NuAno {
            get {
                return this.nuAnoField;
            }
            set {
                this.nuAnoField = value;
                this.RaisePropertyChanged("NuAno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DsCarroceria {
            get {
                return this.dsCarroceriaField;
            }
            set {
                this.dsCarroceriaField = value;
                this.RaisePropertyChanged("DsCarroceria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DsVersao {
            get {
                return this.dsVersaoField;
            }
            set {
                this.dsVersaoField = value;
                this.RaisePropertyChanged("DsVersao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DsMotor {
            get {
                return this.dsMotorField;
            }
            set {
                this.dsMotorField = value;
                this.RaisePropertyChanged("DsMotor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string DsCombustivel {
            get {
                return this.dsCombustivelField;
            }
            set {
                this.dsCombustivelField = value;
                this.RaisePropertyChanged("DsCombustivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DsLocalFabricacao {
            get {
                return this.dsLocalFabricacaoField;
            }
            set {
                this.dsLocalFabricacaoField = value;
                this.RaisePropertyChanged("DsLocalFabricacao");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENTModeloVeiculoPlaca : ENTModeloVeiculo {
        
        private string dsPlacaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DsPlaca {
            get {
                return this.dsPlacaField;
            }
            set {
                this.dsPlacaField = value;
                this.RaisePropertyChanged("DsPlaca");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENTModeloVeiculoValidadorPlaca))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENTModeloVeiculoValidador : ENTModeloVeiculo {
        
        private System.Nullable<int> cdDigitoVerificadorField;
        
        private System.Nullable<int> cdNumeroSerialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> CdDigitoVerificador {
            get {
                return this.cdDigitoVerificadorField;
            }
            set {
                this.cdDigitoVerificadorField = value;
                this.RaisePropertyChanged("CdDigitoVerificador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> CdNumeroSerial {
            get {
                return this.cdNumeroSerialField;
            }
            set {
                this.cdNumeroSerialField = value;
                this.RaisePropertyChanged("CdNumeroSerial");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ENTModeloVeiculoValidadorPlaca : ENTModeloVeiculoValidador {
        
        private string dsPlacaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DsPlaca {
            get {
                return this.dsPlacaField;
            }
            set {
                this.dsPlacaField = value;
                this.RaisePropertyChanged("DsPlaca");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IeDecodificacaoChannel : webServiceCheckOk.WsTecnobank.IeDecodificacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IeDecodificacaoClient : System.ServiceModel.ClientBase<webServiceCheckOk.WsTecnobank.IeDecodificacao>, webServiceCheckOk.WsTecnobank.IeDecodificacao {
        
        public IeDecodificacaoClient() {
        }
        
        public IeDecodificacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IeDecodificacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IeDecodificacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IeDecodificacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public webServiceCheckOk.WsTecnobank.ENTModeloVeiculo DecodificarChassi(string pastrChassi) {
            return base.Channel.DecodificarChassi(pastrChassi);
        }
        
        public System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> DecodificarChassiAsync(string pastrChassi) {
            return base.Channel.DecodificarChassiAsync(pastrChassi);
        }
        
        public webServiceCheckOk.WsTecnobank.ENTModeloVeiculo DecodificarPlaca(string pastrPlaca) {
            return base.Channel.DecodificarPlaca(pastrPlaca);
        }
        
        public System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> DecodificarPlacaAsync(string pastrPlaca) {
            return base.Channel.DecodificarPlacaAsync(pastrPlaca);
        }
        
        public webServiceCheckOk.WsTecnobank.ENTModeloVeiculo PrecificadorChassiI(string pastrChassi) {
            return base.Channel.PrecificadorChassiI(pastrChassi);
        }
        
        public System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> PrecificadorChassiIAsync(string pastrChassi) {
            return base.Channel.PrecificadorChassiIAsync(pastrChassi);
        }
        
        public webServiceCheckOk.WsTecnobank.ENTModeloVeiculo PrecificadorPlacaI(string pastrPlaca) {
            return base.Channel.PrecificadorPlacaI(pastrPlaca);
        }
        
        public System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> PrecificadorPlacaIAsync(string pastrPlaca) {
            return base.Channel.PrecificadorPlacaIAsync(pastrPlaca);
        }
        
        public webServiceCheckOk.WsTecnobank.ENTModeloVeiculo PrecificadorChassiII(string pastrChassi) {
            return base.Channel.PrecificadorChassiII(pastrChassi);
        }
        
        public System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> PrecificadorChassiIIAsync(string pastrChassi) {
            return base.Channel.PrecificadorChassiIIAsync(pastrChassi);
        }
        
        public webServiceCheckOk.WsTecnobank.ENTModeloVeiculo PrecificadorPlacaII(string pastrPlaca) {
            return base.Channel.PrecificadorPlacaII(pastrPlaca);
        }
        
        public System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> PrecificadorPlacaIIAsync(string pastrPlaca) {
            return base.Channel.PrecificadorPlacaIIAsync(pastrPlaca);
        }
        
        public webServiceCheckOk.WsTecnobank.ENTModeloVeiculo DecodificadorPrecificadoresChassi(string pastrChassi) {
            return base.Channel.DecodificadorPrecificadoresChassi(pastrChassi);
        }
        
        public System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> DecodificadorPrecificadoresChassiAsync(string pastrChassi) {
            return base.Channel.DecodificadorPrecificadoresChassiAsync(pastrChassi);
        }
        
        public webServiceCheckOk.WsTecnobank.ENTModeloVeiculo DecodificadorPrecificadoresPlaca(string pastrPlaca) {
            return base.Channel.DecodificadorPrecificadoresPlaca(pastrPlaca);
        }
        
        public System.Threading.Tasks.Task<webServiceCheckOk.WsTecnobank.ENTModeloVeiculo> DecodificadorPrecificadoresPlacaAsync(string pastrPlaca) {
            return base.Channel.DecodificadorPrecificadoresPlacaAsync(pastrPlaca);
        }
    }
}
