//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace webServiceCheckOk.WsSeape {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VeicularNewSoap", Namespace="http://webservice.seape.com.br/")]
    public partial class VeicularNew : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecConsultaGeralOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VeicularNew() {
            this.Url = global::webServiceCheckOk.Properties.Settings.Default.webServiceCheckOk_WsSeape_VeicularNew;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecConsultaCompletedEventHandler ExecConsultaCompleted;
        
        /// <remarks/>
        public event ExecConsultaGeralCompletedEventHandler ExecConsultaGeralCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.seape.com.br/ExecConsulta", RequestNamespace="http://webservice.seape.com.br/", ResponseNamespace="http://webservice.seape.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExecConsulta(int ConsultaID, string TOKEN, string UserName, string Password, string PLACA, string CHASSI, string MOTOR, string CAMBIO, string RENAVAM, string UF, string CPF_CNPJ, string DDD, string TELEFONE) {
            object[] results = this.Invoke("ExecConsulta", new object[] {
                        ConsultaID,
                        TOKEN,
                        UserName,
                        Password,
                        PLACA,
                        CHASSI,
                        MOTOR,
                        CAMBIO,
                        RENAVAM,
                        UF,
                        CPF_CNPJ,
                        DDD,
                        TELEFONE});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExecConsultaAsync(int ConsultaID, string TOKEN, string UserName, string Password, string PLACA, string CHASSI, string MOTOR, string CAMBIO, string RENAVAM, string UF, string CPF_CNPJ, string DDD, string TELEFONE) {
            this.ExecConsultaAsync(ConsultaID, TOKEN, UserName, Password, PLACA, CHASSI, MOTOR, CAMBIO, RENAVAM, UF, CPF_CNPJ, DDD, TELEFONE, null);
        }
        
        /// <remarks/>
        public void ExecConsultaAsync(int ConsultaID, string TOKEN, string UserName, string Password, string PLACA, string CHASSI, string MOTOR, string CAMBIO, string RENAVAM, string UF, string CPF_CNPJ, string DDD, string TELEFONE, object userState) {
            if ((this.ExecConsultaOperationCompleted == null)) {
                this.ExecConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecConsultaOperationCompleted);
            }
            this.InvokeAsync("ExecConsulta", new object[] {
                        ConsultaID,
                        TOKEN,
                        UserName,
                        Password,
                        PLACA,
                        CHASSI,
                        MOTOR,
                        CAMBIO,
                        RENAVAM,
                        UF,
                        CPF_CNPJ,
                        DDD,
                        TELEFONE}, this.ExecConsultaOperationCompleted, userState);
        }
        
        private void OnExecConsultaOperationCompleted(object arg) {
            if ((this.ExecConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecConsultaCompleted(this, new ExecConsultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.seape.com.br/ExecConsultaGeral", RequestNamespace="http://webservice.seape.com.br/", ResponseNamespace="http://webservice.seape.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExecConsultaGeral(int ConsultaID, string TOKEN, string UserName, string Password, string ObjHeader) {
            object[] results = this.Invoke("ExecConsultaGeral", new object[] {
                        ConsultaID,
                        TOKEN,
                        UserName,
                        Password,
                        ObjHeader});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExecConsultaGeralAsync(int ConsultaID, string TOKEN, string UserName, string Password, string ObjHeader) {
            this.ExecConsultaGeralAsync(ConsultaID, TOKEN, UserName, Password, ObjHeader, null);
        }
        
        /// <remarks/>
        public void ExecConsultaGeralAsync(int ConsultaID, string TOKEN, string UserName, string Password, string ObjHeader, object userState) {
            if ((this.ExecConsultaGeralOperationCompleted == null)) {
                this.ExecConsultaGeralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecConsultaGeralOperationCompleted);
            }
            this.InvokeAsync("ExecConsultaGeral", new object[] {
                        ConsultaID,
                        TOKEN,
                        UserName,
                        Password,
                        ObjHeader}, this.ExecConsultaGeralOperationCompleted, userState);
        }
        
        private void OnExecConsultaGeralOperationCompleted(object arg) {
            if ((this.ExecConsultaGeralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecConsultaGeralCompleted(this, new ExecConsultaGeralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ExecConsultaCompletedEventHandler(object sender, ExecConsultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecConsultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecConsultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ExecConsultaGeralCompletedEventHandler(object sender, ExecConsultaGeralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecConsultaGeralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecConsultaGeralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591